# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\QtUI\edit_career_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_EditCareerDialog(object):
    def setupUi(self, EditCareerDialog):
        EditCareerDialog.setObjectName("EditCareerDialog")
        EditCareerDialog.resize(779, 811)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EditCareerDialog.sizePolicy().hasHeightForWidth())
        EditCareerDialog.setSizePolicy(sizePolicy)
        self.vl_ecd_main = QtWidgets.QVBoxLayout(EditCareerDialog)
        self.vl_ecd_main.setObjectName("vl_ecd_main")
        self.hl_ecd_career_desc = QtWidgets.QHBoxLayout()
        self.hl_ecd_career_desc.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hl_ecd_career_desc.setObjectName("hl_ecd_career_desc")
        self.gb_ecd_career = QtWidgets.QGroupBox(EditCareerDialog)
        self.gb_ecd_career.setObjectName("gb_ecd_career")
        self.hl_ecd_career = QtWidgets.QHBoxLayout(self.gb_ecd_career)
        self.hl_ecd_career.setObjectName("hl_ecd_career")
        self.fl_ecd_source_buttons = QtWidgets.QFormLayout()
        self.fl_ecd_source_buttons.setObjectName("fl_ecd_source_buttons")
        self.rb_ecd_old = QtWidgets.QRadioButton(self.gb_ecd_career)
        self.rb_ecd_old.setObjectName("rb_ecd_old")
        self.fl_ecd_source_buttons.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.rb_ecd_old)
        self.rb_ecd_now = QtWidgets.QRadioButton(self.gb_ecd_career)
        self.rb_ecd_now.setObjectName("rb_ecd_now")
        self.fl_ecd_source_buttons.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.rb_ecd_now)
        self.rb_ecd_new = QtWidgets.QRadioButton(self.gb_ecd_career)
        self.rb_ecd_new.setObjectName("rb_ecd_new")
        self.fl_ecd_source_buttons.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.rb_ecd_new)
        self.rb_ecd_custom = QtWidgets.QRadioButton(self.gb_ecd_career)
        self.rb_ecd_custom.setObjectName("rb_ecd_custom")
        self.fl_ecd_source_buttons.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.rb_ecd_custom)
        self.rb_ecd_martial_arts = QtWidgets.QRadioButton(self.gb_ecd_career)
        self.rb_ecd_martial_arts.setObjectName("rb_ecd_martial_arts")
        self.fl_ecd_source_buttons.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.rb_ecd_martial_arts)
        self.rb_ecd_origins = QtWidgets.QRadioButton(self.gb_ecd_career)
        self.rb_ecd_origins.setObjectName("rb_ecd_origins")
        self.fl_ecd_source_buttons.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.rb_ecd_origins)
        self.hl_ecd_career.addLayout(self.fl_ecd_source_buttons)
        self.lw_ecd_careers_val = QtWidgets.QListWidget(self.gb_ecd_career)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lw_ecd_careers_val.sizePolicy().hasHeightForWidth())
        self.lw_ecd_careers_val.setSizePolicy(sizePolicy)
        self.lw_ecd_careers_val.setMinimumSize(QtCore.QSize(200, 0))
        self.lw_ecd_careers_val.setObjectName("lw_ecd_careers_val")
        self.hl_ecd_career.addWidget(self.lw_ecd_careers_val)
        self.hl_ecd_career_desc.addWidget(self.gb_ecd_career)
        self.gb_ecd_career_desc = QtWidgets.QGroupBox(EditCareerDialog)
        self.gb_ecd_career_desc.setObjectName("gb_ecd_career_desc")
        self.vl_ecd_career_desc = QtWidgets.QVBoxLayout(self.gb_ecd_career_desc)
        self.vl_ecd_career_desc.setObjectName("vl_ecd_career_desc")
        self.pte_ecd_career_desc = QtWidgets.QPlainTextEdit(self.gb_ecd_career_desc)
        self.pte_ecd_career_desc.setReadOnly(True)
        self.pte_ecd_career_desc.setObjectName("pte_ecd_career_desc")
        self.vl_ecd_career_desc.addWidget(self.pte_ecd_career_desc)
        self.hl_ecd_career_desc.addWidget(self.gb_ecd_career_desc)
        self.hl_ecd_career_desc.setStretch(0, 1)
        self.hl_ecd_career_desc.setStretch(1, 2)
        self.vl_ecd_main.addLayout(self.hl_ecd_career_desc)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gb_ecd_available_skills = QtWidgets.QGroupBox(EditCareerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_ecd_available_skills.sizePolicy().hasHeightForWidth())
        self.gb_ecd_available_skills.setSizePolicy(sizePolicy)
        self.gb_ecd_available_skills.setMinimumSize(QtCore.QSize(0, 100))
        self.gb_ecd_available_skills.setObjectName("gb_ecd_available_skills")
        self.vl_ecd_available_skills = QtWidgets.QVBoxLayout(self.gb_ecd_available_skills)
        self.vl_ecd_available_skills.setObjectName("vl_ecd_available_skills")
        self.pte_ecd_available_skills = QtWidgets.QPlainTextEdit(self.gb_ecd_available_skills)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pte_ecd_available_skills.sizePolicy().hasHeightForWidth())
        self.pte_ecd_available_skills.setSizePolicy(sizePolicy)
        self.pte_ecd_available_skills.setMinimumSize(QtCore.QSize(0, 0))
        self.pte_ecd_available_skills.setReadOnly(True)
        self.pte_ecd_available_skills.setObjectName("pte_ecd_available_skills")
        self.vl_ecd_available_skills.addWidget(self.pte_ecd_available_skills)
        self.horizontalLayout.addWidget(self.gb_ecd_available_skills)
        self.gb_ecd_current_skills = QtWidgets.QGroupBox(EditCareerDialog)
        self.gb_ecd_current_skills.setObjectName("gb_ecd_current_skills")
        self.vl_ecd_current_skills = QtWidgets.QVBoxLayout(self.gb_ecd_current_skills)
        self.vl_ecd_current_skills.setObjectName("vl_ecd_current_skills")
        self.pte_ecd_current_skills = QtWidgets.QPlainTextEdit(self.gb_ecd_current_skills)
        self.pte_ecd_current_skills.setReadOnly(True)
        self.pte_ecd_current_skills.setObjectName("pte_ecd_current_skills")
        self.vl_ecd_current_skills.addWidget(self.pte_ecd_current_skills)
        self.horizontalLayout.addWidget(self.gb_ecd_current_skills)
        self.vl_ecd_main.addLayout(self.horizontalLayout)
        self.hl_ecd_exploits_desc = QtWidgets.QHBoxLayout()
        self.hl_ecd_exploits_desc.setObjectName("hl_ecd_exploits_desc")
        self.gb_ecd_exploits = QtWidgets.QGroupBox(EditCareerDialog)
        self.gb_ecd_exploits.setObjectName("gb_ecd_exploits")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gb_ecd_exploits)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lw_ecd_exploits_val = QtWidgets.QListWidget(self.gb_ecd_exploits)
        self.lw_ecd_exploits_val.setObjectName("lw_ecd_exploits_val")
        self.verticalLayout_6.addWidget(self.lw_ecd_exploits_val)
        self.hl_ecd_exploits_desc.addWidget(self.gb_ecd_exploits)
        self.gb_ecd_exploit_desc = QtWidgets.QGroupBox(EditCareerDialog)
        self.gb_ecd_exploit_desc.setObjectName("gb_ecd_exploit_desc")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gb_ecd_exploit_desc)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pte_ecd_exploit_desc = QtWidgets.QPlainTextEdit(self.gb_ecd_exploit_desc)
        self.pte_ecd_exploit_desc.setReadOnly(True)
        self.pte_ecd_exploit_desc.setObjectName("pte_ecd_exploit_desc")
        self.verticalLayout_5.addWidget(self.pte_ecd_exploit_desc)
        self.hl_ecd_exploits_desc.addWidget(self.gb_ecd_exploit_desc)
        self.hl_ecd_exploits_desc.setStretch(0, 2)
        self.hl_ecd_exploits_desc.setStretch(1, 3)
        self.vl_ecd_main.addLayout(self.hl_ecd_exploits_desc)
        self.gb_ecd_stats = QtWidgets.QGroupBox(EditCareerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_ecd_stats.sizePolicy().hasHeightForWidth())
        self.gb_ecd_stats.setSizePolicy(sizePolicy)
        self.gb_ecd_stats.setObjectName("gb_ecd_stats")
        self.gridLayout = QtWidgets.QGridLayout(self.gb_ecd_stats)
        self.gridLayout.setObjectName("gridLayout")
        self.l_ecd_str = QtWidgets.QLabel(self.gb_ecd_stats)
        self.l_ecd_str.setObjectName("l_ecd_str")
        self.gridLayout.addWidget(self.l_ecd_str, 0, 0, 1, 1)
        self.l_ecd_end = QtWidgets.QLabel(self.gb_ecd_stats)
        self.l_ecd_end.setObjectName("l_ecd_end")
        self.gridLayout.addWidget(self.l_ecd_end, 0, 2, 1, 1)
        self.l_ecd_int = QtWidgets.QLabel(self.gb_ecd_stats)
        self.l_ecd_int.setObjectName("l_ecd_int")
        self.gridLayout.addWidget(self.l_ecd_int, 0, 3, 1, 1)
        self.l_ecd_log = QtWidgets.QLabel(self.gb_ecd_stats)
        self.l_ecd_log.setObjectName("l_ecd_log")
        self.gridLayout.addWidget(self.l_ecd_log, 0, 4, 1, 1)
        self.l_ecd_wil = QtWidgets.QLabel(self.gb_ecd_stats)
        self.l_ecd_wil.setObjectName("l_ecd_wil")
        self.gridLayout.addWidget(self.l_ecd_wil, 0, 5, 1, 1)
        self.l_ecd_agi = QtWidgets.QLabel(self.gb_ecd_stats)
        self.l_ecd_agi.setObjectName("l_ecd_agi")
        self.gridLayout.addWidget(self.l_ecd_agi, 0, 1, 1, 1)
        self.l_ecd_rep = QtWidgets.QLabel(self.gb_ecd_stats)
        self.l_ecd_rep.setObjectName("l_ecd_rep")
        self.gridLayout.addWidget(self.l_ecd_rep, 0, 8, 1, 1)
        self.l_ecd_mag = QtWidgets.QLabel(self.gb_ecd_stats)
        self.l_ecd_mag.setObjectName("l_ecd_mag")
        self.gridLayout.addWidget(self.l_ecd_mag, 0, 9, 1, 1)
        self.l_ecd_luc = QtWidgets.QLabel(self.gb_ecd_stats)
        self.l_ecd_luc.setObjectName("l_ecd_luc")
        self.gridLayout.addWidget(self.l_ecd_luc, 0, 7, 1, 1)
        self.l_ecd_cha = QtWidgets.QLabel(self.gb_ecd_stats)
        self.l_ecd_cha.setObjectName("l_ecd_cha")
        self.gridLayout.addWidget(self.l_ecd_cha, 0, 6, 1, 1)
        self.l_ecd_chi = QtWidgets.QLabel(self.gb_ecd_stats)
        self.l_ecd_chi.setObjectName("l_ecd_chi")
        self.gridLayout.addWidget(self.l_ecd_chi, 0, 10, 1, 1)
        self.l_ecd_psi = QtWidgets.QLabel(self.gb_ecd_stats)
        self.l_ecd_psi.setObjectName("l_ecd_psi")
        self.gridLayout.addWidget(self.l_ecd_psi, 0, 11, 1, 1)
        self.sb_ecd_log_val = QtWidgets.QSpinBox(self.gb_ecd_stats)
        self.sb_ecd_log_val.setMinimum(-99)
        self.sb_ecd_log_val.setObjectName("sb_ecd_log_val")
        self.gridLayout.addWidget(self.sb_ecd_log_val, 1, 4, 1, 1)
        self.sb_ecd_str_val = QtWidgets.QSpinBox(self.gb_ecd_stats)
        self.sb_ecd_str_val.setMinimum(-99)
        self.sb_ecd_str_val.setObjectName("sb_ecd_str_val")
        self.gridLayout.addWidget(self.sb_ecd_str_val, 1, 0, 1, 1)
        self.sb_ecd_agi_val = QtWidgets.QSpinBox(self.gb_ecd_stats)
        self.sb_ecd_agi_val.setMinimum(-99)
        self.sb_ecd_agi_val.setObjectName("sb_ecd_agi_val")
        self.gridLayout.addWidget(self.sb_ecd_agi_val, 1, 1, 1, 1)
        self.sb_ecd_end_val = QtWidgets.QSpinBox(self.gb_ecd_stats)
        self.sb_ecd_end_val.setMinimum(-99)
        self.sb_ecd_end_val.setObjectName("sb_ecd_end_val")
        self.gridLayout.addWidget(self.sb_ecd_end_val, 1, 2, 1, 1)
        self.sb_ecd_int_val = QtWidgets.QSpinBox(self.gb_ecd_stats)
        self.sb_ecd_int_val.setMinimum(-99)
        self.sb_ecd_int_val.setObjectName("sb_ecd_int_val")
        self.gridLayout.addWidget(self.sb_ecd_int_val, 1, 3, 1, 1)
        self.sb_ecd_wil_val = QtWidgets.QSpinBox(self.gb_ecd_stats)
        self.sb_ecd_wil_val.setMinimum(-99)
        self.sb_ecd_wil_val.setObjectName("sb_ecd_wil_val")
        self.gridLayout.addWidget(self.sb_ecd_wil_val, 1, 5, 1, 1)
        self.sb_ecd_cha_val = QtWidgets.QSpinBox(self.gb_ecd_stats)
        self.sb_ecd_cha_val.setMinimum(-99)
        self.sb_ecd_cha_val.setObjectName("sb_ecd_cha_val")
        self.gridLayout.addWidget(self.sb_ecd_cha_val, 1, 6, 1, 1)
        self.sb_ecd_luc_val = QtWidgets.QSpinBox(self.gb_ecd_stats)
        self.sb_ecd_luc_val.setMinimum(-99)
        self.sb_ecd_luc_val.setObjectName("sb_ecd_luc_val")
        self.gridLayout.addWidget(self.sb_ecd_luc_val, 1, 7, 1, 1)
        self.sb_ecd_rep_val = QtWidgets.QSpinBox(self.gb_ecd_stats)
        self.sb_ecd_rep_val.setMinimum(-99)
        self.sb_ecd_rep_val.setObjectName("sb_ecd_rep_val")
        self.gridLayout.addWidget(self.sb_ecd_rep_val, 1, 8, 1, 1)
        self.sb_ecd_mag_val = QtWidgets.QSpinBox(self.gb_ecd_stats)
        self.sb_ecd_mag_val.setMinimum(-99)
        self.sb_ecd_mag_val.setObjectName("sb_ecd_mag_val")
        self.gridLayout.addWidget(self.sb_ecd_mag_val, 1, 9, 1, 1)
        self.sb_ecd_chi_val = QtWidgets.QSpinBox(self.gb_ecd_stats)
        self.sb_ecd_chi_val.setMinimum(-99)
        self.sb_ecd_chi_val.setObjectName("sb_ecd_chi_val")
        self.gridLayout.addWidget(self.sb_ecd_chi_val, 1, 10, 1, 1)
        self.sb_ecd_psi_val = QtWidgets.QSpinBox(self.gb_ecd_stats)
        self.sb_ecd_psi_val.setMinimum(-99)
        self.sb_ecd_psi_val.setObjectName("sb_ecd_psi_val")
        self.gridLayout.addWidget(self.sb_ecd_psi_val, 1, 11, 1, 1)
        self.vl_ecd_main.addWidget(self.gb_ecd_stats)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditCareerDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.vl_ecd_main.addWidget(self.buttonBox)
        self.vl_ecd_main.setStretch(0, 1)
        self.vl_ecd_main.setStretch(2, 2)

        self.retranslateUi(EditCareerDialog)
        self.buttonBox.accepted.connect(EditCareerDialog.accept)
        self.buttonBox.rejected.connect(EditCareerDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(EditCareerDialog)

    def retranslateUi(self, EditCareerDialog):
        _translate = QtCore.QCoreApplication.translate
        EditCareerDialog.setWindowTitle(_translate("EditCareerDialog", "Edit Career - WOIN Character Assistant"))
        self.gb_ecd_career.setTitle(_translate("EditCareerDialog", "Career"))
        self.rb_ecd_old.setText(_translate("EditCareerDialog", "OLD"))
        self.rb_ecd_now.setText(_translate("EditCareerDialog", "NOW"))
        self.rb_ecd_new.setText(_translate("EditCareerDialog", "NEW"))
        self.rb_ecd_custom.setText(_translate("EditCareerDialog", "Custom"))
        self.rb_ecd_martial_arts.setText(_translate("EditCareerDialog", "Martial Arts"))
        self.rb_ecd_origins.setText(_translate("EditCareerDialog", "Origins"))
        self.gb_ecd_career_desc.setTitle(_translate("EditCareerDialog", "Description"))
        self.gb_ecd_available_skills.setTitle(_translate("EditCareerDialog", "Available Skills"))
        self.gb_ecd_current_skills.setTitle(_translate("EditCareerDialog", "Current Skill Totals"))
        self.gb_ecd_exploits.setTitle(_translate("EditCareerDialog", "Exploits"))
        self.gb_ecd_exploit_desc.setTitle(_translate("EditCareerDialog", "Description"))
        self.gb_ecd_stats.setTitle(_translate("EditCareerDialog", "Career Stats"))
        self.l_ecd_str.setText(_translate("EditCareerDialog", "STR"))
        self.l_ecd_end.setText(_translate("EditCareerDialog", "END"))
        self.l_ecd_int.setText(_translate("EditCareerDialog", "INT"))
        self.l_ecd_log.setText(_translate("EditCareerDialog", "LOG"))
        self.l_ecd_wil.setText(_translate("EditCareerDialog", "WIL"))
        self.l_ecd_agi.setText(_translate("EditCareerDialog", "AGI"))
        self.l_ecd_rep.setText(_translate("EditCareerDialog", "REP"))
        self.l_ecd_mag.setText(_translate("EditCareerDialog", "MAG"))
        self.l_ecd_luc.setText(_translate("EditCareerDialog", "LUC"))
        self.l_ecd_cha.setText(_translate("EditCareerDialog", "CHA"))
        self.l_ecd_chi.setText(_translate("EditCareerDialog", "CHI"))
        self.l_ecd_psi.setText(_translate("EditCareerDialog", "PSI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditCareerDialog = QtWidgets.QDialog()
    ui = Ui_EditCareerDialog()
    ui.setupUi(EditCareerDialog)
    EditCareerDialog.show()
    sys.exit(app.exec_())

