# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\QtUI\set_trait_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SetTraitDialog(object):
    def setupUi(self, SetTraitDialog):
        SetTraitDialog.setObjectName("SetTraitDialog")
        SetTraitDialog.resize(773, 628)
        SetTraitDialog.setModal(True)
        self.vl_std = QtWidgets.QVBoxLayout(SetTraitDialog)
        self.vl_std.setObjectName("vl_std")
        self.hl_std_main = QtWidgets.QHBoxLayout()
        self.hl_std_main.setObjectName("hl_std_main")
        self.gb_std_traits = QtWidgets.QGroupBox(SetTraitDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_std_traits.sizePolicy().hasHeightForWidth())
        self.gb_std_traits.setSizePolicy(sizePolicy)
        self.gb_std_traits.setObjectName("gb_std_traits")
        self.vl_std_traits = QtWidgets.QVBoxLayout(self.gb_std_traits)
        self.vl_std_traits.setObjectName("vl_std_traits")
        self.lw_std_traits = QtWidgets.QListWidget(self.gb_std_traits)
        self.lw_std_traits.setObjectName("lw_std_traits")
        self.vl_std_traits.addWidget(self.lw_std_traits)
        self.hl_std_main.addWidget(self.gb_std_traits)
        self.gb_std_description = QtWidgets.QGroupBox(SetTraitDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_std_description.sizePolicy().hasHeightForWidth())
        self.gb_std_description.setSizePolicy(sizePolicy)
        self.gb_std_description.setObjectName("gb_std_description")
        self.vl_std_description = QtWidgets.QVBoxLayout(self.gb_std_description)
        self.vl_std_description.setObjectName("vl_std_description")
        self.pte_std_traits_desc = QtWidgets.QPlainTextEdit(self.gb_std_description)
        self.pte_std_traits_desc.setReadOnly(True)
        self.pte_std_traits_desc.setObjectName("pte_std_traits_desc")
        self.vl_std_description.addWidget(self.pte_std_traits_desc)
        self.hl_std_main.addWidget(self.gb_std_description)
        self.vl_std.addLayout(self.hl_std_main)
        self.gb_std_trait_table = QtWidgets.QGroupBox(SetTraitDialog)
        self.gb_std_trait_table.setObjectName("gb_std_trait_table")
        self.gl_std_tt = QtWidgets.QGridLayout(self.gb_std_trait_table)
        self.gl_std_tt.setObjectName("gl_std_tt")
        self.l_std_tt_high_attribute = QtWidgets.QLabel(self.gb_std_trait_table)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.l_std_tt_high_attribute.setFont(font)
        self.l_std_tt_high_attribute.setObjectName("l_std_tt_high_attribute")
        self.gl_std_tt.addWidget(self.l_std_tt_high_attribute, 0, 1, 1, 1)
        self.l_std_tt_agi = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_agi.setObjectName("l_std_tt_agi")
        self.gl_std_tt.addWidget(self.l_std_tt_agi, 2, 0, 1, 1)
        self.l_std_tt_str = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_str.setObjectName("l_std_tt_str")
        self.gl_std_tt.addWidget(self.l_std_tt_str, 1, 0, 1, 1)
        self.l_std_tt_end = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_end.setObjectName("l_std_tt_end")
        self.gl_std_tt.addWidget(self.l_std_tt_end, 3, 0, 1, 1)
        self.l_std_tt_log = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_log.setObjectName("l_std_tt_log")
        self.gl_std_tt.addWidget(self.l_std_tt_log, 5, 0, 1, 1)
        self.l_std_tt_int = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_int.setObjectName("l_std_tt_int")
        self.gl_std_tt.addWidget(self.l_std_tt_int, 4, 0, 1, 1)
        self.l_std_tt_wil = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_wil.setObjectName("l_std_tt_wil")
        self.gl_std_tt.addWidget(self.l_std_tt_wil, 6, 0, 1, 1)
        self.l_std_tt_attribute = QtWidgets.QLabel(self.gb_std_trait_table)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.l_std_tt_attribute.setFont(font)
        self.l_std_tt_attribute.setObjectName("l_std_tt_attribute")
        self.gl_std_tt.addWidget(self.l_std_tt_attribute, 0, 0, 1, 1)
        self.l_std_tt_cha = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_cha.setObjectName("l_std_tt_cha")
        self.gl_std_tt.addWidget(self.l_std_tt_cha, 7, 0, 1, 1)
        self.l_std_tt_low_attribute = QtWidgets.QLabel(self.gb_std_trait_table)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.l_std_tt_low_attribute.setFont(font)
        self.l_std_tt_low_attribute.setObjectName("l_std_tt_low_attribute")
        self.gl_std_tt.addWidget(self.l_std_tt_low_attribute, 0, 2, 1, 1)
        self.l_std_tt_rep = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_rep.setObjectName("l_std_tt_rep")
        self.gl_std_tt.addWidget(self.l_std_tt_rep, 8, 0, 1, 1)
        self.l_std_tt_high_str = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_high_str.setObjectName("l_std_tt_high_str")
        self.gl_std_tt.addWidget(self.l_std_tt_high_str, 1, 1, 1, 1)
        self.l_std_tt_low_str = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_low_str.setObjectName("l_std_tt_low_str")
        self.gl_std_tt.addWidget(self.l_std_tt_low_str, 1, 2, 1, 1)
        self.l_std_tt_high_agi = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_high_agi.setObjectName("l_std_tt_high_agi")
        self.gl_std_tt.addWidget(self.l_std_tt_high_agi, 2, 1, 1, 1)
        self.l_std_tt_low_agi = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_low_agi.setObjectName("l_std_tt_low_agi")
        self.gl_std_tt.addWidget(self.l_std_tt_low_agi, 2, 2, 1, 1)
        self.l_std_tt_high_end = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_high_end.setObjectName("l_std_tt_high_end")
        self.gl_std_tt.addWidget(self.l_std_tt_high_end, 3, 1, 1, 1)
        self.l_std_tt_low_end = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_low_end.setObjectName("l_std_tt_low_end")
        self.gl_std_tt.addWidget(self.l_std_tt_low_end, 3, 2, 1, 1)
        self.l_std_tt_high_int = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_high_int.setObjectName("l_std_tt_high_int")
        self.gl_std_tt.addWidget(self.l_std_tt_high_int, 4, 1, 1, 1)
        self.l_std_tt_low_int = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_low_int.setObjectName("l_std_tt_low_int")
        self.gl_std_tt.addWidget(self.l_std_tt_low_int, 4, 2, 1, 1)
        self.l_std_tt_high_log = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_high_log.setObjectName("l_std_tt_high_log")
        self.gl_std_tt.addWidget(self.l_std_tt_high_log, 5, 1, 1, 1)
        self.l_std_tt_low_log = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_low_log.setObjectName("l_std_tt_low_log")
        self.gl_std_tt.addWidget(self.l_std_tt_low_log, 5, 2, 1, 1)
        self.l_std_tt_high_wil = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_high_wil.setObjectName("l_std_tt_high_wil")
        self.gl_std_tt.addWidget(self.l_std_tt_high_wil, 6, 1, 1, 1)
        self.l_std_tt_low_wil = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_low_wil.setObjectName("l_std_tt_low_wil")
        self.gl_std_tt.addWidget(self.l_std_tt_low_wil, 6, 2, 1, 1)
        self.l_std_tt_high_cha = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_high_cha.setObjectName("l_std_tt_high_cha")
        self.gl_std_tt.addWidget(self.l_std_tt_high_cha, 7, 1, 1, 1)
        self.l_std_tt_low_cha = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_low_cha.setObjectName("l_std_tt_low_cha")
        self.gl_std_tt.addWidget(self.l_std_tt_low_cha, 7, 2, 1, 1)
        self.l_std_tt_high_rep = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_high_rep.setObjectName("l_std_tt_high_rep")
        self.gl_std_tt.addWidget(self.l_std_tt_high_rep, 8, 1, 1, 1)
        self.l_std_tt_low_rep = QtWidgets.QLabel(self.gb_std_trait_table)
        self.l_std_tt_low_rep.setObjectName("l_std_tt_low_rep")
        self.gl_std_tt.addWidget(self.l_std_tt_low_rep, 8, 2, 1, 1)
        self.gl_std_tt.setColumnStretch(0, 1)
        self.gl_std_tt.setColumnStretch(1, 2)
        self.gl_std_tt.setColumnStretch(2, 2)
        self.vl_std.addWidget(self.gb_std_trait_table)
        self.gb_std_stats = QtWidgets.QGroupBox(SetTraitDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_std_stats.sizePolicy().hasHeightForWidth())
        self.gb_std_stats.setSizePolicy(sizePolicy)
        self.gb_std_stats.setObjectName("gb_std_stats")
        self.gl_std_stats = QtWidgets.QGridLayout(self.gb_std_stats)
        self.gl_std_stats.setObjectName("gl_std_stats")
        self.l_std_str = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_str.setObjectName("l_std_str")
        self.gl_std_stats.addWidget(self.l_std_str, 0, 0, 1, 1)
        self.l_std_agi = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_agi.setObjectName("l_std_agi")
        self.gl_std_stats.addWidget(self.l_std_agi, 0, 1, 1, 1)
        self.l_std_end = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_end.setObjectName("l_std_end")
        self.gl_std_stats.addWidget(self.l_std_end, 0, 2, 1, 1)
        self.l_std_int = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_int.setObjectName("l_std_int")
        self.gl_std_stats.addWidget(self.l_std_int, 0, 3, 1, 1)
        self.l_std_log = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_log.setObjectName("l_std_log")
        self.gl_std_stats.addWidget(self.l_std_log, 0, 4, 1, 1)
        self.l_std_wil = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_wil.setObjectName("l_std_wil")
        self.gl_std_stats.addWidget(self.l_std_wil, 0, 5, 1, 1)
        self.l_std_cha = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_cha.setObjectName("l_std_cha")
        self.gl_std_stats.addWidget(self.l_std_cha, 0, 6, 1, 1)
        self.l_std_luc = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_luc.setObjectName("l_std_luc")
        self.gl_std_stats.addWidget(self.l_std_luc, 0, 7, 1, 1)
        self.l_std_rep = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_rep.setObjectName("l_std_rep")
        self.gl_std_stats.addWidget(self.l_std_rep, 0, 8, 1, 1)
        self.l_std_mag = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_mag.setObjectName("l_std_mag")
        self.gl_std_stats.addWidget(self.l_std_mag, 0, 9, 1, 1)
        self.l_std_chi = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_chi.setObjectName("l_std_chi")
        self.gl_std_stats.addWidget(self.l_std_chi, 0, 10, 1, 1)
        self.l_std_psi = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_psi.setObjectName("l_std_psi")
        self.gl_std_stats.addWidget(self.l_std_psi, 0, 11, 1, 1)
        self.l_std_str_val = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_str_val.setObjectName("l_std_str_val")
        self.gl_std_stats.addWidget(self.l_std_str_val, 1, 0, 1, 1)
        self.l_std_agi_val = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_agi_val.setObjectName("l_std_agi_val")
        self.gl_std_stats.addWidget(self.l_std_agi_val, 1, 1, 1, 1)
        self.l_std_end_val = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_end_val.setObjectName("l_std_end_val")
        self.gl_std_stats.addWidget(self.l_std_end_val, 1, 2, 1, 1)
        self.l_std_int_val = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_int_val.setObjectName("l_std_int_val")
        self.gl_std_stats.addWidget(self.l_std_int_val, 1, 3, 1, 1)
        self.l_std_log_val = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_log_val.setObjectName("l_std_log_val")
        self.gl_std_stats.addWidget(self.l_std_log_val, 1, 4, 1, 1)
        self.l_std_wil_val = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_wil_val.setObjectName("l_std_wil_val")
        self.gl_std_stats.addWidget(self.l_std_wil_val, 1, 5, 1, 1)
        self.l_std_cha_val = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_cha_val.setObjectName("l_std_cha_val")
        self.gl_std_stats.addWidget(self.l_std_cha_val, 1, 6, 1, 1)
        self.l_std_luc_val = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_luc_val.setObjectName("l_std_luc_val")
        self.gl_std_stats.addWidget(self.l_std_luc_val, 1, 7, 1, 1)
        self.l_std_rep_val = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_rep_val.setObjectName("l_std_rep_val")
        self.gl_std_stats.addWidget(self.l_std_rep_val, 1, 8, 1, 1)
        self.l_std_mag_val = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_mag_val.setObjectName("l_std_mag_val")
        self.gl_std_stats.addWidget(self.l_std_mag_val, 1, 9, 1, 1)
        self.l_std_chi_val = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_chi_val.setObjectName("l_std_chi_val")
        self.gl_std_stats.addWidget(self.l_std_chi_val, 1, 10, 1, 1)
        self.l_std_psi_val = QtWidgets.QLabel(self.gb_std_stats)
        self.l_std_psi_val.setObjectName("l_std_psi_val")
        self.gl_std_stats.addWidget(self.l_std_psi_val, 1, 11, 1, 1)
        self.vl_std.addWidget(self.gb_std_stats)
        self.buttonBox = QtWidgets.QDialogButtonBox(SetTraitDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.vl_std.addWidget(self.buttonBox)

        self.retranslateUi(SetTraitDialog)
        self.buttonBox.accepted.connect(SetTraitDialog.accept)
        self.buttonBox.rejected.connect(SetTraitDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SetTraitDialog)

    def retranslateUi(self, SetTraitDialog):
        _translate = QtCore.QCoreApplication.translate
        SetTraitDialog.setWindowTitle(_translate("SetTraitDialog", "Set Trait - WCA"))
        self.gb_std_traits.setTitle(_translate("SetTraitDialog", "Traits"))
        self.gb_std_description.setTitle(_translate("SetTraitDialog", "Description"))
        self.gb_std_trait_table.setTitle(_translate("SetTraitDialog", "Attribute-Trait Table"))
        self.l_std_tt_high_attribute.setText(_translate("SetTraitDialog", "Highest Attribute"))
        self.l_std_tt_agi.setText(_translate("SetTraitDialog", "AGI"))
        self.l_std_tt_str.setText(_translate("SetTraitDialog", "STR"))
        self.l_std_tt_end.setText(_translate("SetTraitDialog", "END"))
        self.l_std_tt_log.setText(_translate("SetTraitDialog", "LOG"))
        self.l_std_tt_int.setText(_translate("SetTraitDialog", "INT"))
        self.l_std_tt_wil.setText(_translate("SetTraitDialog", "WIL"))
        self.l_std_tt_attribute.setText(_translate("SetTraitDialog", "Attribute"))
        self.l_std_tt_cha.setText(_translate("SetTraitDialog", "CHA"))
        self.l_std_tt_low_attribute.setText(_translate("SetTraitDialog", "Lowest Attribute"))
        self.l_std_tt_rep.setText(_translate("SetTraitDialog", "REP"))
        self.l_std_tt_high_str.setText(_translate("SetTraitDialog", "Massive, Athletic, Brawny"))
        self.l_std_tt_low_str.setText(_translate("SetTraitDialog", "Feeble, Tottering"))
        self.l_std_tt_high_agi.setText(_translate("SetTraitDialog", "Nimble, Deadeye, Ambidextrous"))
        self.l_std_tt_low_agi.setText(_translate("SetTraitDialog", "Clumsy, Lame"))
        self.l_std_tt_high_end.setText(_translate("SetTraitDialog", "Rugged, Tough-as-nails"))
        self.l_std_tt_low_end.setText(_translate("SetTraitDialog", "Coughing, Asthmatic/anemic"))
        self.l_std_tt_high_int.setText(_translate("SetTraitDialog", "Empathic, Alert"))
        self.l_std_tt_low_int.setText(_translate("SetTraitDialog", "Naive, Distracted"))
        self.l_std_tt_high_log.setText(_translate("SetTraitDialog", "Brilliant, Erudite"))
        self.l_std_tt_low_log.setText(_translate("SetTraitDialog", "Illiterate, Forgetful"))
        self.l_std_tt_high_wil.setText(_translate("SetTraitDialog", "Stoid, Unflappable"))
        self.l_std_tt_low_wil.setText(_translate("SetTraitDialog", "Alcoholic, Reckless, Spendthrift"))
        self.l_std_tt_high_cha.setText(_translate("SetTraitDialog", "Commanding, Inspiring, Suave, Persuasive"))
        self.l_std_tt_low_cha.setText(_translate("SetTraitDialog", "Unwashed, Disfigured, Obnoxious"))
        self.l_std_tt_high_rep.setText(_translate("SetTraitDialog", "Well-known, Egotistical"))
        self.l_std_tt_low_rep.setText(_translate("SetTraitDialog", "-"))
        self.gb_std_stats.setTitle(_translate("SetTraitDialog", "Total Stats"))
        self.l_std_str.setText(_translate("SetTraitDialog", "STR"))
        self.l_std_agi.setText(_translate("SetTraitDialog", "AGI"))
        self.l_std_end.setText(_translate("SetTraitDialog", "END"))
        self.l_std_int.setText(_translate("SetTraitDialog", "INT"))
        self.l_std_log.setText(_translate("SetTraitDialog", "LOG"))
        self.l_std_wil.setText(_translate("SetTraitDialog", "WIL"))
        self.l_std_cha.setText(_translate("SetTraitDialog", "CHA"))
        self.l_std_luc.setText(_translate("SetTraitDialog", "LUC"))
        self.l_std_rep.setText(_translate("SetTraitDialog", "REP"))
        self.l_std_mag.setText(_translate("SetTraitDialog", "MAG"))
        self.l_std_chi.setText(_translate("SetTraitDialog", "CHI"))
        self.l_std_psi.setText(_translate("SetTraitDialog", "PSI"))
        self.l_std_str_val.setText(_translate("SetTraitDialog", "str_val"))
        self.l_std_agi_val.setText(_translate("SetTraitDialog", "agi_val"))
        self.l_std_end_val.setText(_translate("SetTraitDialog", "end_val"))
        self.l_std_int_val.setText(_translate("SetTraitDialog", "int_val"))
        self.l_std_log_val.setText(_translate("SetTraitDialog", "log_val"))
        self.l_std_wil_val.setText(_translate("SetTraitDialog", "wil_val"))
        self.l_std_cha_val.setText(_translate("SetTraitDialog", "cha_val"))
        self.l_std_luc_val.setText(_translate("SetTraitDialog", "luc_val"))
        self.l_std_rep_val.setText(_translate("SetTraitDialog", "rep_val"))
        self.l_std_mag_val.setText(_translate("SetTraitDialog", "mag_val"))
        self.l_std_chi_val.setText(_translate("SetTraitDialog", "chi_val"))
        self.l_std_psi_val.setText(_translate("SetTraitDialog", "psi_val"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SetTraitDialog = QtWidgets.QDialog()
    ui = Ui_SetTraitDialog()
    ui.setupUi(SetTraitDialog)
    SetTraitDialog.show()
    sys.exit(app.exec_())

