# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\QtUI\set_homeworld_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_SetHomeworldDialog(object):
    def setupUi(self, SetHomeworldDialog):
        SetHomeworldDialog.setObjectName("SetHomeworldDialog")
        SetHomeworldDialog.resize(663, 357)
        self.vl_shd_main = QtWidgets.QVBoxLayout(SetHomeworldDialog)
        self.vl_shd_main.setObjectName("vl_shd_main")
        self.hl_shd_homeworld_and_skills = QtWidgets.QHBoxLayout()
        self.hl_shd_homeworld_and_skills.setObjectName("hl_shd_homeworld_and_skills")
        self.gb_shd_homeworld = QtWidgets.QGroupBox(SetHomeworldDialog)
        self.gb_shd_homeworld.setObjectName("gb_shd_homeworld")
        self.hl_shd_homeworld = QtWidgets.QHBoxLayout(self.gb_shd_homeworld)
        self.hl_shd_homeworld.setObjectName("hl_shd_homeworld")
        self.fl_shd_homeworld_buttons = QtWidgets.QFormLayout()
        self.fl_shd_homeworld_buttons.setObjectName("fl_shd_homeworld_buttons")
        self.rb_shd_new = QtWidgets.QRadioButton(self.gb_shd_homeworld)
        self.rb_shd_new.setObjectName("rb_shd_new")
        self.fl_shd_homeworld_buttons.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.rb_shd_new)
        self.rb_shd_custom = QtWidgets.QRadioButton(self.gb_shd_homeworld)
        self.rb_shd_custom.setObjectName("rb_shd_custom")
        self.fl_shd_homeworld_buttons.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.rb_shd_custom)
        self.hl_shd_homeworld.addLayout(self.fl_shd_homeworld_buttons)
        self.lw_shd_homeworlds_val = QtWidgets.QListWidget(self.gb_shd_homeworld)
        self.lw_shd_homeworlds_val.setObjectName("lw_shd_homeworlds_val")
        self.hl_shd_homeworld.addWidget(self.lw_shd_homeworlds_val)
        self.hl_shd_homeworld_and_skills.addWidget(self.gb_shd_homeworld)
        self.gb_shd_skills = QtWidgets.QGroupBox(SetHomeworldDialog)
        self.gb_shd_skills.setObjectName("gb_shd_skills")
        self.vl_shd_skills = QtWidgets.QVBoxLayout(self.gb_shd_skills)
        self.vl_shd_skills.setObjectName("vl_shd_skills")
        self.pte_shd_skills = QtWidgets.QPlainTextEdit(self.gb_shd_skills)
        self.pte_shd_skills.setReadOnly(True)
        self.pte_shd_skills.setObjectName("pte_shd_skills")
        self.vl_shd_skills.addWidget(self.pte_shd_skills)
        self.hl_shd_homeworld_and_skills.addWidget(self.gb_shd_skills)
        self.hl_shd_homeworld_and_skills.setStretch(0, 3)
        self.hl_shd_homeworld_and_skills.setStretch(1, 4)
        self.vl_shd_main.addLayout(self.hl_shd_homeworld_and_skills)
        self.gb_shd_stats = QtWidgets.QGroupBox(SetHomeworldDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_shd_stats.sizePolicy().hasHeightForWidth())
        self.gb_shd_stats.setSizePolicy(sizePolicy)
        self.gb_shd_stats.setObjectName("gb_shd_stats")
        self.gl_shd_stats = QtWidgets.QGridLayout(self.gb_shd_stats)
        self.gl_shd_stats.setObjectName("gl_shd_stats")
        self.l_shd_str = QtWidgets.QLabel(self.gb_shd_stats)
        self.l_shd_str.setObjectName("l_shd_str")
        self.gl_shd_stats.addWidget(self.l_shd_str, 0, 0, 1, 1)
        self.l_shd_agi = QtWidgets.QLabel(self.gb_shd_stats)
        self.l_shd_agi.setObjectName("l_shd_agi")
        self.gl_shd_stats.addWidget(self.l_shd_agi, 0, 1, 1, 1)
        self.l_shd_end = QtWidgets.QLabel(self.gb_shd_stats)
        self.l_shd_end.setObjectName("l_shd_end")
        self.gl_shd_stats.addWidget(self.l_shd_end, 0, 2, 1, 1)
        self.l_shd_int = QtWidgets.QLabel(self.gb_shd_stats)
        self.l_shd_int.setObjectName("l_shd_int")
        self.gl_shd_stats.addWidget(self.l_shd_int, 0, 3, 1, 1)
        self.l_shd_log = QtWidgets.QLabel(self.gb_shd_stats)
        self.l_shd_log.setObjectName("l_shd_log")
        self.gl_shd_stats.addWidget(self.l_shd_log, 0, 4, 1, 1)
        self.l_shd_wil = QtWidgets.QLabel(self.gb_shd_stats)
        self.l_shd_wil.setObjectName("l_shd_wil")
        self.gl_shd_stats.addWidget(self.l_shd_wil, 0, 5, 1, 1)
        self.l_shd_cha = QtWidgets.QLabel(self.gb_shd_stats)
        self.l_shd_cha.setObjectName("l_shd_cha")
        self.gl_shd_stats.addWidget(self.l_shd_cha, 0, 6, 1, 1)
        self.l_shd_luc = QtWidgets.QLabel(self.gb_shd_stats)
        self.l_shd_luc.setObjectName("l_shd_luc")
        self.gl_shd_stats.addWidget(self.l_shd_luc, 0, 7, 1, 1)
        self.l_shd_rep = QtWidgets.QLabel(self.gb_shd_stats)
        self.l_shd_rep.setObjectName("l_shd_rep")
        self.gl_shd_stats.addWidget(self.l_shd_rep, 0, 8, 1, 1)
        self.l_shd_mag = QtWidgets.QLabel(self.gb_shd_stats)
        self.l_shd_mag.setObjectName("l_shd_mag")
        self.gl_shd_stats.addWidget(self.l_shd_mag, 0, 9, 1, 1)
        self.l_shd_chi = QtWidgets.QLabel(self.gb_shd_stats)
        self.l_shd_chi.setObjectName("l_shd_chi")
        self.gl_shd_stats.addWidget(self.l_shd_chi, 0, 10, 1, 1)
        self.l_shd_psi = QtWidgets.QLabel(self.gb_shd_stats)
        self.l_shd_psi.setObjectName("l_shd_psi")
        self.gl_shd_stats.addWidget(self.l_shd_psi, 0, 11, 1, 1)
        self.sb_shd_str_val = QtWidgets.QSpinBox(self.gb_shd_stats)
        self.sb_shd_str_val.setMinimum(-99)
        self.sb_shd_str_val.setObjectName("sb_shd_str_val")
        self.gl_shd_stats.addWidget(self.sb_shd_str_val, 1, 0, 1, 1)
        self.sb_shd_agi_val = QtWidgets.QSpinBox(self.gb_shd_stats)
        self.sb_shd_agi_val.setMinimum(-99)
        self.sb_shd_agi_val.setObjectName("sb_shd_agi_val")
        self.gl_shd_stats.addWidget(self.sb_shd_agi_val, 1, 1, 1, 1)
        self.sb_shd_end_val = QtWidgets.QSpinBox(self.gb_shd_stats)
        self.sb_shd_end_val.setMinimum(-99)
        self.sb_shd_end_val.setObjectName("sb_shd_end_val")
        self.gl_shd_stats.addWidget(self.sb_shd_end_val, 1, 2, 1, 1)
        self.sb_shd_int_val = QtWidgets.QSpinBox(self.gb_shd_stats)
        self.sb_shd_int_val.setMinimum(-99)
        self.sb_shd_int_val.setObjectName("sb_shd_int_val")
        self.gl_shd_stats.addWidget(self.sb_shd_int_val, 1, 3, 1, 1)
        self.sb_shd_log_val = QtWidgets.QSpinBox(self.gb_shd_stats)
        self.sb_shd_log_val.setMinimum(-99)
        self.sb_shd_log_val.setObjectName("sb_shd_log_val")
        self.gl_shd_stats.addWidget(self.sb_shd_log_val, 1, 4, 1, 1)
        self.sb_shd_wil_val = QtWidgets.QSpinBox(self.gb_shd_stats)
        self.sb_shd_wil_val.setMinimum(-99)
        self.sb_shd_wil_val.setObjectName("sb_shd_wil_val")
        self.gl_shd_stats.addWidget(self.sb_shd_wil_val, 1, 5, 1, 1)
        self.sb_shd_cha_val = QtWidgets.QSpinBox(self.gb_shd_stats)
        self.sb_shd_cha_val.setMinimum(-99)
        self.sb_shd_cha_val.setObjectName("sb_shd_cha_val")
        self.gl_shd_stats.addWidget(self.sb_shd_cha_val, 1, 6, 1, 1)
        self.sb_shd_luc_val = QtWidgets.QSpinBox(self.gb_shd_stats)
        self.sb_shd_luc_val.setMinimum(-99)
        self.sb_shd_luc_val.setObjectName("sb_shd_luc_val")
        self.gl_shd_stats.addWidget(self.sb_shd_luc_val, 1, 7, 1, 1)
        self.sb_shd_rep_val = QtWidgets.QSpinBox(self.gb_shd_stats)
        self.sb_shd_rep_val.setMinimum(-99)
        self.sb_shd_rep_val.setObjectName("sb_shd_rep_val")
        self.gl_shd_stats.addWidget(self.sb_shd_rep_val, 1, 8, 1, 1)
        self.sb_shd_mag_val = QtWidgets.QSpinBox(self.gb_shd_stats)
        self.sb_shd_mag_val.setMinimum(-99)
        self.sb_shd_mag_val.setObjectName("sb_shd_mag_val")
        self.gl_shd_stats.addWidget(self.sb_shd_mag_val, 1, 9, 1, 1)
        self.sb_shd_chi_val = QtWidgets.QSpinBox(self.gb_shd_stats)
        self.sb_shd_chi_val.setMinimum(-99)
        self.sb_shd_chi_val.setObjectName("sb_shd_chi_val")
        self.gl_shd_stats.addWidget(self.sb_shd_chi_val, 1, 10, 1, 1)
        self.sb_shd_psi_val = QtWidgets.QSpinBox(self.gb_shd_stats)
        self.sb_shd_psi_val.setMinimum(-99)
        self.sb_shd_psi_val.setObjectName("sb_shd_psi_val")
        self.gl_shd_stats.addWidget(self.sb_shd_psi_val, 1, 11, 1, 1)
        self.vl_shd_main.addWidget(self.gb_shd_stats)
        self.buttonBox = QtWidgets.QDialogButtonBox(SetHomeworldDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.vl_shd_main.addWidget(self.buttonBox)

        self.retranslateUi(SetHomeworldDialog)
        self.buttonBox.accepted.connect(SetHomeworldDialog.accept)
        self.buttonBox.rejected.connect(SetHomeworldDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SetHomeworldDialog)

    def retranslateUi(self, SetHomeworldDialog):
        _translate = QtCore.QCoreApplication.translate
        SetHomeworldDialog.setWindowTitle(_translate("SetHomeworldDialog", "Set Homeworld - WOIN Character Assistant"))
        self.gb_shd_homeworld.setTitle(_translate("SetHomeworldDialog", "Homeworld"))
        self.rb_shd_new.setText(_translate("SetHomeworldDialog", "NEW"))
        self.rb_shd_custom.setText(_translate("SetHomeworldDialog", "Custom"))
        self.gb_shd_skills.setTitle(_translate("SetHomeworldDialog", "Available Skills"))
        self.gb_shd_stats.setTitle(_translate("SetHomeworldDialog", "Homeworld Stats"))
        self.l_shd_str.setText(_translate("SetHomeworldDialog", "STR"))
        self.l_shd_agi.setText(_translate("SetHomeworldDialog", "AGI"))
        self.l_shd_end.setText(_translate("SetHomeworldDialog", "END"))
        self.l_shd_int.setText(_translate("SetHomeworldDialog", "INT"))
        self.l_shd_log.setText(_translate("SetHomeworldDialog", "LOG"))
        self.l_shd_wil.setText(_translate("SetHomeworldDialog", "WIL"))
        self.l_shd_cha.setText(_translate("SetHomeworldDialog", "CHA"))
        self.l_shd_luc.setText(_translate("SetHomeworldDialog", "LUC"))
        self.l_shd_rep.setText(_translate("SetHomeworldDialog", "REP"))
        self.l_shd_mag.setText(_translate("SetHomeworldDialog", "MAG"))
        self.l_shd_chi.setText(_translate("SetHomeworldDialog", "CHI"))
        self.l_shd_psi.setText(_translate("SetHomeworldDialog", "PSI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SetHomeworldDialog = QtWidgets.QDialog()
    ui = Ui_SetHomeworldDialog()
    ui.setupUi(SetHomeworldDialog)
    SetHomeworldDialog.show()
    sys.exit(app.exec_())

