# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\QtUI\set_race_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_SetRaceDialog(object):
    def setupUi(self, SetRaceDialog):
        SetRaceDialog.setObjectName("SetRaceDialog")
        SetRaceDialog.resize(779, 811)
        self.verticalLayout = QtWidgets.QVBoxLayout(SetRaceDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hl_srd_race_desc = QtWidgets.QHBoxLayout()
        self.hl_srd_race_desc.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hl_srd_race_desc.setObjectName("hl_srd_race_desc")
        self.gb_srd_race = QtWidgets.QGroupBox(SetRaceDialog)
        self.gb_srd_race.setObjectName("gb_srd_race")
        self.hl_srd_race = QtWidgets.QHBoxLayout(self.gb_srd_race)
        self.hl_srd_race.setObjectName("hl_srd_race")
        self.fl_srd_source_buttons = QtWidgets.QFormLayout()
        self.fl_srd_source_buttons.setObjectName("fl_srd_source_buttons")
        self.rb_srd_old = QtWidgets.QRadioButton(self.gb_srd_race)
        self.rb_srd_old.setObjectName("rb_srd_old")
        self.fl_srd_source_buttons.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.rb_srd_old)
        self.rb_srd_now = QtWidgets.QRadioButton(self.gb_srd_race)
        self.rb_srd_now.setObjectName("rb_srd_now")
        self.fl_srd_source_buttons.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.rb_srd_now)
        self.rb_srd_new = QtWidgets.QRadioButton(self.gb_srd_race)
        self.rb_srd_new.setObjectName("rb_srd_new")
        self.fl_srd_source_buttons.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.rb_srd_new)
        self.rb_srd_custom = QtWidgets.QRadioButton(self.gb_srd_race)
        self.rb_srd_custom.setObjectName("rb_srd_custom")
        self.fl_srd_source_buttons.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.rb_srd_custom)
        self.hl_srd_race.addLayout(self.fl_srd_source_buttons)
        self.lw_srd_races_val = QtWidgets.QListWidget(self.gb_srd_race)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lw_srd_races_val.sizePolicy().hasHeightForWidth())
        self.lw_srd_races_val.setSizePolicy(sizePolicy)
        self.lw_srd_races_val.setMinimumSize(QtCore.QSize(200, 0))
        self.lw_srd_races_val.setObjectName("lw_srd_races_val")
        self.hl_srd_race.addWidget(self.lw_srd_races_val)
        self.hl_srd_race_desc.addWidget(self.gb_srd_race)
        self.gb_srd_race_desc = QtWidgets.QGroupBox(SetRaceDialog)
        self.gb_srd_race_desc.setObjectName("gb_srd_race_desc")
        self.vl_srd_race_desc = QtWidgets.QVBoxLayout(self.gb_srd_race_desc)
        self.vl_srd_race_desc.setObjectName("vl_srd_race_desc")
        self.pte_srd_race_desc = QtWidgets.QPlainTextEdit(self.gb_srd_race_desc)
        self.pte_srd_race_desc.setReadOnly(True)
        self.pte_srd_race_desc.setObjectName("pte_srd_race_desc")
        self.vl_srd_race_desc.addWidget(self.pte_srd_race_desc)
        self.hl_srd_race_desc.addWidget(self.gb_srd_race_desc)
        self.hl_srd_race_desc.setStretch(0, 1)
        self.hl_srd_race_desc.setStretch(1, 2)
        self.verticalLayout.addLayout(self.hl_srd_race_desc)
        self.gb_srd_skills = QtWidgets.QGroupBox(SetRaceDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_srd_skills.sizePolicy().hasHeightForWidth())
        self.gb_srd_skills.setSizePolicy(sizePolicy)
        self.gb_srd_skills.setMinimumSize(QtCore.QSize(0, 100))
        self.gb_srd_skills.setObjectName("gb_srd_skills")
        self.vl_srd_skills = QtWidgets.QVBoxLayout(self.gb_srd_skills)
        self.vl_srd_skills.setObjectName("vl_srd_skills")
        self.pte_srd_skills = QtWidgets.QPlainTextEdit(self.gb_srd_skills)
        self.pte_srd_skills.setMinimumSize(QtCore.QSize(0, 0))
        self.pte_srd_skills.setReadOnly(True)
        self.pte_srd_skills.setObjectName("pte_srd_skills")
        self.vl_srd_skills.addWidget(self.pte_srd_skills)
        self.verticalLayout.addWidget(self.gb_srd_skills)
        self.hl_srd_exploits_desc = QtWidgets.QHBoxLayout()
        self.hl_srd_exploits_desc.setObjectName("hl_srd_exploits_desc")
        self.gb_srd_exploits = QtWidgets.QGroupBox(SetRaceDialog)
        self.gb_srd_exploits.setObjectName("gb_srd_exploits")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gb_srd_exploits)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lw_srd_exploits_val = QtWidgets.QListWidget(self.gb_srd_exploits)
        self.lw_srd_exploits_val.setObjectName("lw_srd_exploits_val")
        self.verticalLayout_6.addWidget(self.lw_srd_exploits_val)
        self.hl_srd_exploits_desc.addWidget(self.gb_srd_exploits)
        self.gb_srd_exploit_desc = QtWidgets.QGroupBox(SetRaceDialog)
        self.gb_srd_exploit_desc.setObjectName("gb_srd_exploit_desc")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gb_srd_exploit_desc)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pte_srd_exploit_desc = QtWidgets.QPlainTextEdit(self.gb_srd_exploit_desc)
        self.pte_srd_exploit_desc.setReadOnly(True)
        self.pte_srd_exploit_desc.setObjectName("pte_srd_exploit_desc")
        self.verticalLayout_5.addWidget(self.pte_srd_exploit_desc)
        self.hl_srd_exploits_desc.addWidget(self.gb_srd_exploit_desc)
        self.hl_srd_exploits_desc.setStretch(0, 2)
        self.hl_srd_exploits_desc.setStretch(1, 3)
        self.verticalLayout.addLayout(self.hl_srd_exploits_desc)
        self.gb_srd_stats = QtWidgets.QGroupBox(SetRaceDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_srd_stats.sizePolicy().hasHeightForWidth())
        self.gb_srd_stats.setSizePolicy(sizePolicy)
        self.gb_srd_stats.setObjectName("gb_srd_stats")
        self.gridLayout = QtWidgets.QGridLayout(self.gb_srd_stats)
        self.gridLayout.setObjectName("gridLayout")
        self.l_srd_str = QtWidgets.QLabel(self.gb_srd_stats)
        self.l_srd_str.setObjectName("l_srd_str")
        self.gridLayout.addWidget(self.l_srd_str, 0, 0, 1, 1)
        self.l_srd_end = QtWidgets.QLabel(self.gb_srd_stats)
        self.l_srd_end.setObjectName("l_srd_end")
        self.gridLayout.addWidget(self.l_srd_end, 0, 2, 1, 1)
        self.l_srd_int = QtWidgets.QLabel(self.gb_srd_stats)
        self.l_srd_int.setObjectName("l_srd_int")
        self.gridLayout.addWidget(self.l_srd_int, 0, 3, 1, 1)
        self.l_srd_log = QtWidgets.QLabel(self.gb_srd_stats)
        self.l_srd_log.setObjectName("l_srd_log")
        self.gridLayout.addWidget(self.l_srd_log, 0, 4, 1, 1)
        self.l_srd_wil = QtWidgets.QLabel(self.gb_srd_stats)
        self.l_srd_wil.setObjectName("l_srd_wil")
        self.gridLayout.addWidget(self.l_srd_wil, 0, 5, 1, 1)
        self.l_srd_agi = QtWidgets.QLabel(self.gb_srd_stats)
        self.l_srd_agi.setObjectName("l_srd_agi")
        self.gridLayout.addWidget(self.l_srd_agi, 0, 1, 1, 1)
        self.l_srd_rep = QtWidgets.QLabel(self.gb_srd_stats)
        self.l_srd_rep.setObjectName("l_srd_rep")
        self.gridLayout.addWidget(self.l_srd_rep, 0, 8, 1, 1)
        self.l_srd_mag = QtWidgets.QLabel(self.gb_srd_stats)
        self.l_srd_mag.setObjectName("l_srd_mag")
        self.gridLayout.addWidget(self.l_srd_mag, 0, 9, 1, 1)
        self.l_srd_luc = QtWidgets.QLabel(self.gb_srd_stats)
        self.l_srd_luc.setObjectName("l_srd_luc")
        self.gridLayout.addWidget(self.l_srd_luc, 0, 7, 1, 1)
        self.l_srd_cha = QtWidgets.QLabel(self.gb_srd_stats)
        self.l_srd_cha.setObjectName("l_srd_cha")
        self.gridLayout.addWidget(self.l_srd_cha, 0, 6, 1, 1)
        self.l_srd_chi = QtWidgets.QLabel(self.gb_srd_stats)
        self.l_srd_chi.setObjectName("l_srd_chi")
        self.gridLayout.addWidget(self.l_srd_chi, 0, 10, 1, 1)
        self.l_srd_psi = QtWidgets.QLabel(self.gb_srd_stats)
        self.l_srd_psi.setObjectName("l_srd_psi")
        self.gridLayout.addWidget(self.l_srd_psi, 0, 11, 1, 1)
        self.sb_srd_log_val = QtWidgets.QSpinBox(self.gb_srd_stats)
        self.sb_srd_log_val.setMinimum(-99)
        self.sb_srd_log_val.setObjectName("sb_srd_log_val")
        self.gridLayout.addWidget(self.sb_srd_log_val, 1, 4, 1, 1)
        self.sb_srd_str_val = QtWidgets.QSpinBox(self.gb_srd_stats)
        self.sb_srd_str_val.setMinimum(-99)
        self.sb_srd_str_val.setObjectName("sb_srd_str_val")
        self.gridLayout.addWidget(self.sb_srd_str_val, 1, 0, 1, 1)
        self.sb_srd_agi_val = QtWidgets.QSpinBox(self.gb_srd_stats)
        self.sb_srd_agi_val.setMinimum(-99)
        self.sb_srd_agi_val.setObjectName("sb_srd_agi_val")
        self.gridLayout.addWidget(self.sb_srd_agi_val, 1, 1, 1, 1)
        self.sb_srd_end_val = QtWidgets.QSpinBox(self.gb_srd_stats)
        self.sb_srd_end_val.setMinimum(-99)
        self.sb_srd_end_val.setObjectName("sb_srd_end_val")
        self.gridLayout.addWidget(self.sb_srd_end_val, 1, 2, 1, 1)
        self.sb_srd_int_val = QtWidgets.QSpinBox(self.gb_srd_stats)
        self.sb_srd_int_val.setMinimum(-99)
        self.sb_srd_int_val.setObjectName("sb_srd_int_val")
        self.gridLayout.addWidget(self.sb_srd_int_val, 1, 3, 1, 1)
        self.sb_srd_wil_val = QtWidgets.QSpinBox(self.gb_srd_stats)
        self.sb_srd_wil_val.setMinimum(-99)
        self.sb_srd_wil_val.setObjectName("sb_srd_wil_val")
        self.gridLayout.addWidget(self.sb_srd_wil_val, 1, 5, 1, 1)
        self.sb_srd_cha_val = QtWidgets.QSpinBox(self.gb_srd_stats)
        self.sb_srd_cha_val.setMinimum(-99)
        self.sb_srd_cha_val.setObjectName("sb_srd_cha_val")
        self.gridLayout.addWidget(self.sb_srd_cha_val, 1, 6, 1, 1)
        self.sb_srd_luc_val = QtWidgets.QSpinBox(self.gb_srd_stats)
        self.sb_srd_luc_val.setMinimum(-99)
        self.sb_srd_luc_val.setObjectName("sb_srd_luc_val")
        self.gridLayout.addWidget(self.sb_srd_luc_val, 1, 7, 1, 1)
        self.sb_srd_rep_val = QtWidgets.QSpinBox(self.gb_srd_stats)
        self.sb_srd_rep_val.setMinimum(-99)
        self.sb_srd_rep_val.setObjectName("sb_srd_rep_val")
        self.gridLayout.addWidget(self.sb_srd_rep_val, 1, 8, 1, 1)
        self.sb_srd_mag_val = QtWidgets.QSpinBox(self.gb_srd_stats)
        self.sb_srd_mag_val.setMinimum(-99)
        self.sb_srd_mag_val.setObjectName("sb_srd_mag_val")
        self.gridLayout.addWidget(self.sb_srd_mag_val, 1, 9, 1, 1)
        self.sb_srd_chi_val = QtWidgets.QSpinBox(self.gb_srd_stats)
        self.sb_srd_chi_val.setMinimum(-99)
        self.sb_srd_chi_val.setObjectName("sb_srd_chi_val")
        self.gridLayout.addWidget(self.sb_srd_chi_val, 1, 10, 1, 1)
        self.sb_srd_psi_val = QtWidgets.QSpinBox(self.gb_srd_stats)
        self.sb_srd_psi_val.setMinimum(-99)
        self.sb_srd_psi_val.setObjectName("sb_srd_psi_val")
        self.gridLayout.addWidget(self.sb_srd_psi_val, 1, 11, 1, 1)
        self.verticalLayout.addWidget(self.gb_srd_stats)
        self.buttonBox = QtWidgets.QDialogButtonBox(SetRaceDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 2)

        self.retranslateUi(SetRaceDialog)
        self.buttonBox.accepted.connect(SetRaceDialog.accept)
        self.buttonBox.rejected.connect(SetRaceDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SetRaceDialog)

    def retranslateUi(self, SetRaceDialog):
        _translate = QtCore.QCoreApplication.translate
        SetRaceDialog.setWindowTitle(_translate("SetRaceDialog", "Set Race - WOIN Character Assistant"))
        self.gb_srd_race.setTitle(_translate("SetRaceDialog", "Race"))
        self.rb_srd_old.setText(_translate("SetRaceDialog", "OLD"))
        self.rb_srd_now.setText(_translate("SetRaceDialog", "NOW"))
        self.rb_srd_new.setText(_translate("SetRaceDialog", "NEW"))
        self.rb_srd_custom.setText(_translate("SetRaceDialog", "Custom"))
        self.gb_srd_race_desc.setTitle(_translate("SetRaceDialog", "Description"))
        self.gb_srd_skills.setTitle(_translate("SetRaceDialog", "Available Skills"))
        self.gb_srd_exploits.setTitle(_translate("SetRaceDialog", "Exploits"))
        self.gb_srd_exploit_desc.setTitle(_translate("SetRaceDialog", "Description"))
        self.gb_srd_stats.setTitle(_translate("SetRaceDialog", "Racial Stats"))
        self.l_srd_str.setText(_translate("SetRaceDialog", "STR"))
        self.l_srd_end.setText(_translate("SetRaceDialog", "END"))
        self.l_srd_int.setText(_translate("SetRaceDialog", "INT"))
        self.l_srd_log.setText(_translate("SetRaceDialog", "LOG"))
        self.l_srd_wil.setText(_translate("SetRaceDialog", "WIL"))
        self.l_srd_agi.setText(_translate("SetRaceDialog", "AGI"))
        self.l_srd_rep.setText(_translate("SetRaceDialog", "REP"))
        self.l_srd_mag.setText(_translate("SetRaceDialog", "MAG"))
        self.l_srd_luc.setText(_translate("SetRaceDialog", "LUC"))
        self.l_srd_cha.setText(_translate("SetRaceDialog", "CHA"))
        self.l_srd_chi.setText(_translate("SetRaceDialog", "CHI"))
        self.l_srd_psi.setText(_translate("SetRaceDialog", "PSI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SetRaceDialog = QtWidgets.QDialog()
    ui = Ui_SetRaceDialog()
    ui.setupUi(SetRaceDialog)
    SetRaceDialog.show()
    sys.exit(app.exec_())

