# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\QtUI\wca.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1051, 862)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.vl_central_widget = QtWidgets.QVBoxLayout(self.central_widget)
        self.vl_central_widget.setObjectName("vl_central_widget")
        self.tw_main = QtWidgets.QTabWidget(self.central_widget)
        self.tw_main.setEnabled(True)
        self.tw_main.setObjectName("tw_main")
        self.tab_overview = QtWidgets.QWidget()
        self.tab_overview.setObjectName("tab_overview")
        self.vl_overview = QtWidgets.QVBoxLayout(self.tab_overview)
        self.vl_overview.setObjectName("vl_overview")
        self.hl_overview_info_skills = QtWidgets.QHBoxLayout()
        self.hl_overview_info_skills.setObjectName("hl_overview_info_skills")
        self.gb_overview_info = QtWidgets.QGroupBox(self.tab_overview)
        self.gb_overview_info.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_overview_info.sizePolicy().hasHeightForWidth())
        self.gb_overview_info.setSizePolicy(sizePolicy)
        self.gb_overview_info.setFlat(False)
        self.gb_overview_info.setCheckable(False)
        self.gb_overview_info.setObjectName("gb_overview_info")
        self.fl_overview_info = QtWidgets.QFormLayout(self.gb_overview_info)
        self.fl_overview_info.setObjectName("fl_overview_info")
        self.l_overview_name = QtWidgets.QLabel(self.gb_overview_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_overview_name.sizePolicy().hasHeightForWidth())
        self.l_overview_name.setSizePolicy(sizePolicy)
        self.l_overview_name.setObjectName("l_overview_name")
        self.fl_overview_info.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.l_overview_name)
        self.le_overview_name_val = QtWidgets.QLineEdit(self.gb_overview_info)
        self.le_overview_name_val.setFrame(True)
        self.le_overview_name_val.setReadOnly(False)
        self.le_overview_name_val.setObjectName("le_overview_name_val")
        self.fl_overview_info.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_overview_name_val)
        self.l_overview_race = QtWidgets.QLabel(self.gb_overview_info)
        self.l_overview_race.setObjectName("l_overview_race")
        self.fl_overview_info.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.l_overview_race)
        self.l_overview_homeworld = QtWidgets.QLabel(self.gb_overview_info)
        self.l_overview_homeworld.setObjectName("l_overview_homeworld")
        self.fl_overview_info.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.l_overview_homeworld)
        self.l_overview_trait = QtWidgets.QLabel(self.gb_overview_info)
        self.l_overview_trait.setObjectName("l_overview_trait")
        self.fl_overview_info.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.l_overview_trait)
        self.pb_overview_trait_val = QtWidgets.QPushButton(self.gb_overview_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_overview_trait_val.sizePolicy().hasHeightForWidth())
        self.pb_overview_trait_val.setSizePolicy(sizePolicy)
        self.pb_overview_trait_val.setObjectName("pb_overview_trait_val")
        self.fl_overview_info.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pb_overview_trait_val)
        self.l_overview_hook = QtWidgets.QLabel(self.gb_overview_info)
        self.l_overview_hook.setObjectName("l_overview_hook")
        self.fl_overview_info.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.l_overview_hook)
        self.le_overview_hook_val = QtWidgets.QLineEdit(self.gb_overview_info)
        self.le_overview_hook_val.setObjectName("le_overview_hook_val")
        self.fl_overview_info.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.le_overview_hook_val)
        self.l_overview_race_val = QtWidgets.QLabel(self.gb_overview_info)
        self.l_overview_race_val.setObjectName("l_overview_race_val")
        self.fl_overview_info.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.l_overview_race_val)
        self.l_overview_homeworld_val = QtWidgets.QLabel(self.gb_overview_info)
        self.l_overview_homeworld_val.setObjectName("l_overview_homeworld_val")
        self.fl_overview_info.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.l_overview_homeworld_val)
        self.hl_overview_info_skills.addWidget(self.gb_overview_info)
        self.gb_overview_skills = QtWidgets.QGroupBox(self.tab_overview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_overview_skills.sizePolicy().hasHeightForWidth())
        self.gb_overview_skills.setSizePolicy(sizePolicy)
        self.gb_overview_skills.setObjectName("gb_overview_skills")
        self.vl_overview_skills = QtWidgets.QVBoxLayout(self.gb_overview_skills)
        self.vl_overview_skills.setObjectName("vl_overview_skills")
        self.pte_overview_skills_val = QtWidgets.QPlainTextEdit(self.gb_overview_skills)
        self.pte_overview_skills_val.setReadOnly(True)
        self.pte_overview_skills_val.setBackgroundVisible(False)
        self.pte_overview_skills_val.setObjectName("pte_overview_skills_val")
        self.vl_overview_skills.addWidget(self.pte_overview_skills_val)
        self.hl_overview_info_skills.addWidget(self.gb_overview_skills)
        self.vl_overview.addLayout(self.hl_overview_info_skills)
        self.gb_overview_exploits = QtWidgets.QGroupBox(self.tab_overview)
        self.gb_overview_exploits.setObjectName("gb_overview_exploits")
        self.vl_overview_exploits = QtWidgets.QVBoxLayout(self.gb_overview_exploits)
        self.vl_overview_exploits.setObjectName("vl_overview_exploits")
        self.pte_overview_exploits_val = QtWidgets.QPlainTextEdit(self.gb_overview_exploits)
        self.pte_overview_exploits_val.setReadOnly(True)
        self.pte_overview_exploits_val.setObjectName("pte_overview_exploits_val")
        self.vl_overview_exploits.addWidget(self.pte_overview_exploits_val)
        self.vl_overview.addWidget(self.gb_overview_exploits)
        self.gb_overview_derived_stats = QtWidgets.QGroupBox(self.tab_overview)
        self.gb_overview_derived_stats.setObjectName("gb_overview_derived_stats")
        self.vl_overview_derived_stats = QtWidgets.QVBoxLayout(self.gb_overview_derived_stats)
        self.vl_overview_derived_stats.setObjectName("vl_overview_derived_stats")
        self.hl_overview_health_initiative = QtWidgets.QHBoxLayout()
        self.hl_overview_health_initiative.setObjectName("hl_overview_health_initiative")
        self.gb_overview_health = QtWidgets.QGroupBox(self.gb_overview_derived_stats)
        self.gb_overview_health.setObjectName("gb_overview_health")
        self.hl_overview_health = QtWidgets.QHBoxLayout(self.gb_overview_health)
        self.hl_overview_health.setObjectName("hl_overview_health")
        self.l_overview_health_val = QtWidgets.QLabel(self.gb_overview_health)
        self.l_overview_health_val.setObjectName("l_overview_health_val")
        self.hl_overview_health.addWidget(self.l_overview_health_val)
        self.hl_overview_health_initiative.addWidget(self.gb_overview_health)
        self.gb_overview_initiative = QtWidgets.QGroupBox(self.gb_overview_derived_stats)
        self.gb_overview_initiative.setObjectName("gb_overview_initiative")
        self.hl_overview_initiative = QtWidgets.QHBoxLayout(self.gb_overview_initiative)
        self.hl_overview_initiative.setObjectName("hl_overview_initiative")
        self.l_overview_initiative_val = QtWidgets.QLabel(self.gb_overview_initiative)
        self.l_overview_initiative_val.setObjectName("l_overview_initiative_val")
        self.hl_overview_initiative.addWidget(self.l_overview_initiative_val)
        self.hl_overview_health_initiative.addWidget(self.gb_overview_initiative)
        self.vl_overview_derived_stats.addLayout(self.hl_overview_health_initiative)
        self.hl_overview_movement_defenses = QtWidgets.QHBoxLayout()
        self.hl_overview_movement_defenses.setObjectName("hl_overview_movement_defenses")
        self.gb_overview_movement = QtWidgets.QGroupBox(self.gb_overview_derived_stats)
        self.gb_overview_movement.setObjectName("gb_overview_movement")
        self.fl_overview_movement = QtWidgets.QFormLayout(self.gb_overview_movement)
        self.fl_overview_movement.setObjectName("fl_overview_movement")
        self.l_overview_speed = QtWidgets.QLabel(self.gb_overview_movement)
        self.l_overview_speed.setObjectName("l_overview_speed")
        self.fl_overview_movement.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.l_overview_speed)
        self.l_overview_speed_val = QtWidgets.QLabel(self.gb_overview_movement)
        self.l_overview_speed_val.setObjectName("l_overview_speed_val")
        self.fl_overview_movement.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.l_overview_speed_val)
        self.l_overview_climb = QtWidgets.QLabel(self.gb_overview_movement)
        self.l_overview_climb.setObjectName("l_overview_climb")
        self.fl_overview_movement.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.l_overview_climb)
        self.l_overview_swim = QtWidgets.QLabel(self.gb_overview_movement)
        self.l_overview_swim.setObjectName("l_overview_swim")
        self.fl_overview_movement.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.l_overview_swim)
        self.l_overview_zlhg = QtWidgets.QLabel(self.gb_overview_movement)
        self.l_overview_zlhg.setObjectName("l_overview_zlhg")
        self.fl_overview_movement.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.l_overview_zlhg)
        self.l_overview_vertical_jump = QtWidgets.QLabel(self.gb_overview_movement)
        self.l_overview_vertical_jump.setObjectName("l_overview_vertical_jump")
        self.fl_overview_movement.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.l_overview_vertical_jump)
        self.l_overview_horizontal_jump = QtWidgets.QLabel(self.gb_overview_movement)
        self.l_overview_horizontal_jump.setObjectName("l_overview_horizontal_jump")
        self.fl_overview_movement.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.l_overview_horizontal_jump)
        self.l_overview_carry = QtWidgets.QLabel(self.gb_overview_movement)
        self.l_overview_carry.setObjectName("l_overview_carry")
        self.fl_overview_movement.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.l_overview_carry)
        self.l_overview_climb_val = QtWidgets.QLabel(self.gb_overview_movement)
        self.l_overview_climb_val.setObjectName("l_overview_climb_val")
        self.fl_overview_movement.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.l_overview_climb_val)
        self.l_overview_swim_val = QtWidgets.QLabel(self.gb_overview_movement)
        self.l_overview_swim_val.setObjectName("l_overview_swim_val")
        self.fl_overview_movement.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.l_overview_swim_val)
        self.l_overview_zlhg_val = QtWidgets.QLabel(self.gb_overview_movement)
        self.l_overview_zlhg_val.setObjectName("l_overview_zlhg_val")
        self.fl_overview_movement.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.l_overview_zlhg_val)
        self.l_overview_vertical_jump_val = QtWidgets.QLabel(self.gb_overview_movement)
        self.l_overview_vertical_jump_val.setObjectName("l_overview_vertical_jump_val")
        self.fl_overview_movement.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.l_overview_vertical_jump_val)
        self.l_overview_horizontal_jump_val = QtWidgets.QLabel(self.gb_overview_movement)
        self.l_overview_horizontal_jump_val.setObjectName("l_overview_horizontal_jump_val")
        self.fl_overview_movement.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.l_overview_horizontal_jump_val)
        self.l_overview_carry_val = QtWidgets.QLabel(self.gb_overview_movement)
        self.l_overview_carry_val.setObjectName("l_overview_carry_val")
        self.fl_overview_movement.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.l_overview_carry_val)
        self.hl_overview_movement_defenses.addWidget(self.gb_overview_movement)
        self.gb_overview_defenses = QtWidgets.QGroupBox(self.gb_overview_derived_stats)
        self.gb_overview_defenses.setObjectName("gb_overview_defenses")
        self.fl_overview_defenses = QtWidgets.QFormLayout(self.gb_overview_defenses)
        self.fl_overview_defenses.setObjectName("fl_overview_defenses")
        self.l_overview_melee_def = QtWidgets.QLabel(self.gb_overview_defenses)
        self.l_overview_melee_def.setObjectName("l_overview_melee_def")
        self.fl_overview_defenses.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.l_overview_melee_def)
        self.l_overview_melee_def_val = QtWidgets.QLabel(self.gb_overview_defenses)
        self.l_overview_melee_def_val.setObjectName("l_overview_melee_def_val")
        self.fl_overview_defenses.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.l_overview_melee_def_val)
        self.l_overview_ranged_def = QtWidgets.QLabel(self.gb_overview_defenses)
        self.l_overview_ranged_def.setObjectName("l_overview_ranged_def")
        self.fl_overview_defenses.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.l_overview_ranged_def)
        self.l_overview_ranged_def_val = QtWidgets.QLabel(self.gb_overview_defenses)
        self.l_overview_ranged_def_val.setObjectName("l_overview_ranged_def_val")
        self.fl_overview_defenses.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.l_overview_ranged_def_val)
        self.l_overview_mental_def = QtWidgets.QLabel(self.gb_overview_defenses)
        self.l_overview_mental_def.setObjectName("l_overview_mental_def")
        self.fl_overview_defenses.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.l_overview_mental_def)
        self.l_overview_mental_def_val = QtWidgets.QLabel(self.gb_overview_defenses)
        self.l_overview_mental_def_val.setObjectName("l_overview_mental_def_val")
        self.fl_overview_defenses.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.l_overview_mental_def_val)
        self.l_overview_vital_def = QtWidgets.QLabel(self.gb_overview_defenses)
        self.l_overview_vital_def.setObjectName("l_overview_vital_def")
        self.fl_overview_defenses.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.l_overview_vital_def)
        self.l_overview_vital_def_val = QtWidgets.QLabel(self.gb_overview_defenses)
        self.l_overview_vital_def_val.setObjectName("l_overview_vital_def_val")
        self.fl_overview_defenses.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.l_overview_vital_def_val)
        self.pb_set_defense_skills = QtWidgets.QPushButton(self.gb_overview_defenses)
        self.pb_set_defense_skills.setObjectName("pb_set_defense_skills")
        self.fl_overview_defenses.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pb_set_defense_skills)
        self.hl_overview_movement_defenses.addWidget(self.gb_overview_defenses)
        self.vl_overview_derived_stats.addLayout(self.hl_overview_movement_defenses)
        self.vl_overview.addWidget(self.gb_overview_derived_stats)
        self.gb_overview_stats = QtWidgets.QGroupBox(self.tab_overview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_overview_stats.sizePolicy().hasHeightForWidth())
        self.gb_overview_stats.setSizePolicy(sizePolicy)
        self.gb_overview_stats.setObjectName("gb_overview_stats")
        self.gl_overview_stats = QtWidgets.QGridLayout(self.gb_overview_stats)
        self.gl_overview_stats.setObjectName("gl_overview_stats")
        self.l_overview_rep = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_rep.setObjectName("l_overview_rep")
        self.gl_overview_stats.addWidget(self.l_overview_rep, 0, 8, 1, 1)
        self.l_overview_cha = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_cha.setObjectName("l_overview_cha")
        self.gl_overview_stats.addWidget(self.l_overview_cha, 0, 6, 1, 1)
        self.l_overview_psi = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_psi.setObjectName("l_overview_psi")
        self.gl_overview_stats.addWidget(self.l_overview_psi, 0, 11, 1, 1)
        self.l_overview_chi = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_chi.setObjectName("l_overview_chi")
        self.gl_overview_stats.addWidget(self.l_overview_chi, 0, 10, 1, 1)
        self.l_overview_end = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_end.setObjectName("l_overview_end")
        self.gl_overview_stats.addWidget(self.l_overview_end, 0, 2, 1, 1)
        self.l_overview_int = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_int.setObjectName("l_overview_int")
        self.gl_overview_stats.addWidget(self.l_overview_int, 0, 3, 1, 1)
        self.l_overview_mag = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_mag.setObjectName("l_overview_mag")
        self.gl_overview_stats.addWidget(self.l_overview_mag, 0, 9, 1, 1)
        self.l_overview_str = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_str.setObjectName("l_overview_str")
        self.gl_overview_stats.addWidget(self.l_overview_str, 0, 0, 1, 1)
        self.l_overview_wil = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_wil.setObjectName("l_overview_wil")
        self.gl_overview_stats.addWidget(self.l_overview_wil, 0, 5, 1, 1)
        self.l_overview_agi = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_agi.setObjectName("l_overview_agi")
        self.gl_overview_stats.addWidget(self.l_overview_agi, 0, 1, 1, 1)
        self.l_overview_log = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_log.setObjectName("l_overview_log")
        self.gl_overview_stats.addWidget(self.l_overview_log, 0, 4, 1, 1)
        self.l_overview_luc = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_luc.setObjectName("l_overview_luc")
        self.gl_overview_stats.addWidget(self.l_overview_luc, 0, 7, 1, 1)
        self.l_overview_str_val = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_str_val.setObjectName("l_overview_str_val")
        self.gl_overview_stats.addWidget(self.l_overview_str_val, 1, 0, 1, 1)
        self.l_overview_agi_val = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_agi_val.setObjectName("l_overview_agi_val")
        self.gl_overview_stats.addWidget(self.l_overview_agi_val, 1, 1, 1, 1)
        self.l_overview_end_val = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_end_val.setObjectName("l_overview_end_val")
        self.gl_overview_stats.addWidget(self.l_overview_end_val, 1, 2, 1, 1)
        self.l_overview_int_val = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_int_val.setObjectName("l_overview_int_val")
        self.gl_overview_stats.addWidget(self.l_overview_int_val, 1, 3, 1, 1)
        self.l_overview_log_val = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_log_val.setObjectName("l_overview_log_val")
        self.gl_overview_stats.addWidget(self.l_overview_log_val, 1, 4, 1, 1)
        self.l_overview_wil_val = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_wil_val.setObjectName("l_overview_wil_val")
        self.gl_overview_stats.addWidget(self.l_overview_wil_val, 1, 5, 1, 1)
        self.l_overview_cha_val = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_cha_val.setObjectName("l_overview_cha_val")
        self.gl_overview_stats.addWidget(self.l_overview_cha_val, 1, 6, 1, 1)
        self.l_overview_luc_val = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_luc_val.setObjectName("l_overview_luc_val")
        self.gl_overview_stats.addWidget(self.l_overview_luc_val, 1, 7, 1, 1)
        self.l_overview_rep_val = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_rep_val.setObjectName("l_overview_rep_val")
        self.gl_overview_stats.addWidget(self.l_overview_rep_val, 1, 8, 1, 1)
        self.l_overview_mag_val = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_mag_val.setObjectName("l_overview_mag_val")
        self.gl_overview_stats.addWidget(self.l_overview_mag_val, 1, 9, 1, 1)
        self.l_overview_chi_val = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_chi_val.setObjectName("l_overview_chi_val")
        self.gl_overview_stats.addWidget(self.l_overview_chi_val, 1, 10, 1, 1)
        self.l_overview_psi_val = QtWidgets.QLabel(self.gb_overview_stats)
        self.l_overview_psi_val.setObjectName("l_overview_psi_val")
        self.gl_overview_stats.addWidget(self.l_overview_psi_val, 1, 11, 1, 1)
        self.vl_overview.addWidget(self.gb_overview_stats)
        self.tw_main.addTab(self.tab_overview, "")
        self.tab_race = QtWidgets.QWidget()
        self.tab_race.setObjectName("tab_race")
        self.vl_race = QtWidgets.QVBoxLayout(self.tab_race)
        self.vl_race.setObjectName("vl_race")
        self.gb_race_race = QtWidgets.QGroupBox(self.tab_race)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_race_race.sizePolicy().hasHeightForWidth())
        self.gb_race_race.setSizePolicy(sizePolicy)
        self.gb_race_race.setObjectName("gb_race_race")
        self.fl_race_race = QtWidgets.QFormLayout(self.gb_race_race)
        self.fl_race_race.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.fl_race_race.setObjectName("fl_race_race")
        self.l_race_race = QtWidgets.QLabel(self.gb_race_race)
        self.l_race_race.setObjectName("l_race_race")
        self.fl_race_race.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.l_race_race)
        self.pb_race_race_val = QtWidgets.QPushButton(self.gb_race_race)
        self.pb_race_race_val.setObjectName("pb_race_race_val")
        self.fl_race_race.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pb_race_race_val)
        self.l_race_size = QtWidgets.QLabel(self.gb_race_race)
        self.l_race_size.setObjectName("l_race_size")
        self.fl_race_race.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.l_race_size)
        self.cb_race_size_val = QtWidgets.QComboBox(self.gb_race_race)
        self.cb_race_size_val.setObjectName("cb_race_size_val")
        self.cb_race_size_val.addItem("")
        self.cb_race_size_val.addItem("")
        self.cb_race_size_val.addItem("")
        self.cb_race_size_val.addItem("")
        self.cb_race_size_val.addItem("")
        self.cb_race_size_val.addItem("")
        self.cb_race_size_val.addItem("")
        self.cb_race_size_val.addItem("")
        self.fl_race_race.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_race_size_val)
        self.vl_race.addWidget(self.gb_race_race)
        self.gb_race_skills = QtWidgets.QGroupBox(self.tab_race)
        self.gb_race_skills.setObjectName("gb_race_skills")
        self.vl_race_skills = QtWidgets.QVBoxLayout(self.gb_race_skills)
        self.vl_race_skills.setObjectName("vl_race_skills")
        self.pte_race_skills_val = QtWidgets.QPlainTextEdit(self.gb_race_skills)
        self.pte_race_skills_val.setObjectName("pte_race_skills_val")
        self.vl_race_skills.addWidget(self.pte_race_skills_val)
        self.pb_race_set_skills = QtWidgets.QPushButton(self.gb_race_skills)
        self.pb_race_set_skills.setDefault(False)
        self.pb_race_set_skills.setFlat(False)
        self.pb_race_set_skills.setObjectName("pb_race_set_skills")
        self.vl_race_skills.addWidget(self.pb_race_set_skills, 0, QtCore.Qt.AlignLeft)
        self.vl_race.addWidget(self.gb_race_skills)
        self.hl_race_exploits_desc = QtWidgets.QHBoxLayout()
        self.hl_race_exploits_desc.setObjectName("hl_race_exploits_desc")
        self.gb_race_exploits = QtWidgets.QGroupBox(self.tab_race)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_race_exploits.sizePolicy().hasHeightForWidth())
        self.gb_race_exploits.setSizePolicy(sizePolicy)
        self.gb_race_exploits.setObjectName("gb_race_exploits")
        self.vl_race_exploits = QtWidgets.QVBoxLayout(self.gb_race_exploits)
        self.vl_race_exploits.setObjectName("vl_race_exploits")
        self.lw_race_exploits_val = QtWidgets.QListWidget(self.gb_race_exploits)
        self.lw_race_exploits_val.setObjectName("lw_race_exploits_val")
        self.vl_race_exploits.addWidget(self.lw_race_exploits_val)
        self.hl_race_exploits_desc.addWidget(self.gb_race_exploits)
        self.gb_race_exploits_desc = QtWidgets.QGroupBox(self.tab_race)
        self.gb_race_exploits_desc.setObjectName("gb_race_exploits_desc")
        self.vl_race_exploits_desc = QtWidgets.QVBoxLayout(self.gb_race_exploits_desc)
        self.vl_race_exploits_desc.setObjectName("vl_race_exploits_desc")
        self.pte_race_exploits_desc = QtWidgets.QPlainTextEdit(self.gb_race_exploits_desc)
        self.pte_race_exploits_desc.setReadOnly(True)
        self.pte_race_exploits_desc.setObjectName("pte_race_exploits_desc")
        self.vl_race_exploits_desc.addWidget(self.pte_race_exploits_desc)
        self.hl_race_exploits_desc.addWidget(self.gb_race_exploits_desc)
        self.vl_race.addLayout(self.hl_race_exploits_desc)
        self.gb_race_stats = QtWidgets.QGroupBox(self.tab_race)
        self.gb_race_stats.setObjectName("gb_race_stats")
        self.gl_race_stats = QtWidgets.QGridLayout(self.gb_race_stats)
        self.gl_race_stats.setObjectName("gl_race_stats")
        self.l_race_str = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_str.setObjectName("l_race_str")
        self.gl_race_stats.addWidget(self.l_race_str, 0, 0, 1, 1)
        self.l_race_agi = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_agi.setObjectName("l_race_agi")
        self.gl_race_stats.addWidget(self.l_race_agi, 0, 1, 1, 1)
        self.l_race_end = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_end.setObjectName("l_race_end")
        self.gl_race_stats.addWidget(self.l_race_end, 0, 2, 1, 1)
        self.l_race_int = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_int.setObjectName("l_race_int")
        self.gl_race_stats.addWidget(self.l_race_int, 0, 3, 1, 1)
        self.l_race_log = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_log.setObjectName("l_race_log")
        self.gl_race_stats.addWidget(self.l_race_log, 0, 4, 1, 1)
        self.l_race_will = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_will.setObjectName("l_race_will")
        self.gl_race_stats.addWidget(self.l_race_will, 0, 5, 1, 1)
        self.l_race_cha = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_cha.setObjectName("l_race_cha")
        self.gl_race_stats.addWidget(self.l_race_cha, 0, 6, 1, 1)
        self.l_race_luc = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_luc.setObjectName("l_race_luc")
        self.gl_race_stats.addWidget(self.l_race_luc, 0, 7, 1, 1)
        self.l_race_rep = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_rep.setObjectName("l_race_rep")
        self.gl_race_stats.addWidget(self.l_race_rep, 0, 8, 1, 1)
        self.l_race_mag = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_mag.setObjectName("l_race_mag")
        self.gl_race_stats.addWidget(self.l_race_mag, 0, 9, 1, 1)
        self.l_race_chi = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_chi.setObjectName("l_race_chi")
        self.gl_race_stats.addWidget(self.l_race_chi, 0, 10, 1, 1)
        self.l_race_psi = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_psi.setObjectName("l_race_psi")
        self.gl_race_stats.addWidget(self.l_race_psi, 0, 11, 1, 1)
        self.l_race_str_val = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_str_val.setObjectName("l_race_str_val")
        self.gl_race_stats.addWidget(self.l_race_str_val, 1, 0, 1, 1)
        self.l_race_agi_val = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_agi_val.setObjectName("l_race_agi_val")
        self.gl_race_stats.addWidget(self.l_race_agi_val, 1, 1, 1, 1)
        self.l_race_end_val = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_end_val.setObjectName("l_race_end_val")
        self.gl_race_stats.addWidget(self.l_race_end_val, 1, 2, 1, 1)
        self.l_race_int_val = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_int_val.setObjectName("l_race_int_val")
        self.gl_race_stats.addWidget(self.l_race_int_val, 1, 3, 1, 1)
        self.l_race_log_val = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_log_val.setObjectName("l_race_log_val")
        self.gl_race_stats.addWidget(self.l_race_log_val, 1, 4, 1, 1)
        self.l_race_wil_val = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_wil_val.setObjectName("l_race_wil_val")
        self.gl_race_stats.addWidget(self.l_race_wil_val, 1, 5, 1, 1)
        self.l_race_cha_val = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_cha_val.setObjectName("l_race_cha_val")
        self.gl_race_stats.addWidget(self.l_race_cha_val, 1, 6, 1, 1)
        self.l_race_luc_val = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_luc_val.setObjectName("l_race_luc_val")
        self.gl_race_stats.addWidget(self.l_race_luc_val, 1, 7, 1, 1)
        self.l_race_rep_val = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_rep_val.setObjectName("l_race_rep_val")
        self.gl_race_stats.addWidget(self.l_race_rep_val, 1, 8, 1, 1)
        self.l_race_mag_val = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_mag_val.setObjectName("l_race_mag_val")
        self.gl_race_stats.addWidget(self.l_race_mag_val, 1, 9, 1, 1)
        self.l_race_chi_val = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_chi_val.setObjectName("l_race_chi_val")
        self.gl_race_stats.addWidget(self.l_race_chi_val, 1, 10, 1, 1)
        self.l_race_psi_val = QtWidgets.QLabel(self.gb_race_stats)
        self.l_race_psi_val.setObjectName("l_race_psi_val")
        self.gl_race_stats.addWidget(self.l_race_psi_val, 1, 11, 1, 1)
        self.vl_race.addWidget(self.gb_race_stats)
        self.tw_main.addTab(self.tab_race, "")
        self.tab_homeworld = QtWidgets.QWidget()
        self.tab_homeworld.setObjectName("tab_homeworld")
        self.vl_homeworld = QtWidgets.QVBoxLayout(self.tab_homeworld)
        self.vl_homeworld.setObjectName("vl_homeworld")
        self.gb_homeworld_homeworld = QtWidgets.QGroupBox(self.tab_homeworld)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_homeworld_homeworld.sizePolicy().hasHeightForWidth())
        self.gb_homeworld_homeworld.setSizePolicy(sizePolicy)
        self.gb_homeworld_homeworld.setObjectName("gb_homeworld_homeworld")
        self.vl_homeworld_homeworld = QtWidgets.QVBoxLayout(self.gb_homeworld_homeworld)
        self.vl_homeworld_homeworld.setObjectName("vl_homeworld_homeworld")
        self.pb_homeworld_homeworld_val = QtWidgets.QPushButton(self.gb_homeworld_homeworld)
        self.pb_homeworld_homeworld_val.setObjectName("pb_homeworld_homeworld_val")
        self.vl_homeworld_homeworld.addWidget(self.pb_homeworld_homeworld_val, 0, QtCore.Qt.AlignLeft)
        self.vl_homeworld.addWidget(self.gb_homeworld_homeworld)
        self.gb_homeworld_skills = QtWidgets.QGroupBox(self.tab_homeworld)
        self.gb_homeworld_skills.setObjectName("gb_homeworld_skills")
        self.vl_homeworld_skills = QtWidgets.QVBoxLayout(self.gb_homeworld_skills)
        self.vl_homeworld_skills.setObjectName("vl_homeworld_skills")
        self.pte_homeworld_skills_val = QtWidgets.QPlainTextEdit(self.gb_homeworld_skills)
        self.pte_homeworld_skills_val.setObjectName("pte_homeworld_skills_val")
        self.vl_homeworld_skills.addWidget(self.pte_homeworld_skills_val)
        self.pb_homeworld_set_skills = QtWidgets.QPushButton(self.gb_homeworld_skills)
        self.pb_homeworld_set_skills.setObjectName("pb_homeworld_set_skills")
        self.vl_homeworld_skills.addWidget(self.pb_homeworld_set_skills, 0, QtCore.Qt.AlignLeft)
        self.vl_homeworld.addWidget(self.gb_homeworld_skills)
        self.gb_homeworld_stats = QtWidgets.QGroupBox(self.tab_homeworld)
        self.gb_homeworld_stats.setObjectName("gb_homeworld_stats")
        self.gl_homeworld_stats = QtWidgets.QGridLayout(self.gb_homeworld_stats)
        self.gl_homeworld_stats.setObjectName("gl_homeworld_stats")
        self.l_homeworld_str = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_str.setObjectName("l_homeworld_str")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_str, 0, 0, 1, 1)
        self.l_homeworld_agi = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_agi.setObjectName("l_homeworld_agi")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_agi, 0, 1, 1, 1)
        self.l_homeworld_end = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_end.setObjectName("l_homeworld_end")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_end, 0, 2, 1, 1)
        self.l_homeworld_int = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_int.setObjectName("l_homeworld_int")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_int, 0, 3, 1, 1)
        self.l_homeworld_log = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_log.setObjectName("l_homeworld_log")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_log, 0, 4, 1, 1)
        self.l_homeworld_wil = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_wil.setObjectName("l_homeworld_wil")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_wil, 0, 5, 1, 1)
        self.l_homeworld_cha = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_cha.setObjectName("l_homeworld_cha")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_cha, 0, 6, 1, 1)
        self.l_homeworld_luc = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_luc.setObjectName("l_homeworld_luc")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_luc, 0, 7, 1, 1)
        self.l_homeworld_rep = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_rep.setObjectName("l_homeworld_rep")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_rep, 0, 8, 1, 1)
        self.l_homeworld_mag = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_mag.setObjectName("l_homeworld_mag")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_mag, 0, 9, 1, 1)
        self.l_homeworld_chi = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_chi.setObjectName("l_homeworld_chi")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_chi, 0, 10, 1, 1)
        self.l_homeworld_psi = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_psi.setObjectName("l_homeworld_psi")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_psi, 0, 11, 1, 1)
        self.l_homeworld_str_val = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_str_val.setObjectName("l_homeworld_str_val")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_str_val, 1, 0, 1, 1)
        self.l_homeworld_agi_val = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_agi_val.setObjectName("l_homeworld_agi_val")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_agi_val, 1, 1, 1, 1)
        self.l_homeworld_end_val = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_end_val.setObjectName("l_homeworld_end_val")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_end_val, 1, 2, 1, 1)
        self.l_homeworld_int_val = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_int_val.setObjectName("l_homeworld_int_val")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_int_val, 1, 3, 1, 1)
        self.l_homeworld_log_val = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_log_val.setObjectName("l_homeworld_log_val")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_log_val, 1, 4, 1, 1)
        self.l_homeworld_wil_val = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_wil_val.setObjectName("l_homeworld_wil_val")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_wil_val, 1, 5, 1, 1)
        self.l_homeworld_cha_val = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_cha_val.setObjectName("l_homeworld_cha_val")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_cha_val, 1, 6, 1, 1)
        self.l_homeworld_luc_val = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_luc_val.setObjectName("l_homeworld_luc_val")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_luc_val, 1, 7, 1, 1)
        self.l_homeworld_rep_val = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_rep_val.setObjectName("l_homeworld_rep_val")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_rep_val, 1, 8, 1, 1)
        self.l_homeworld_mag_val = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_mag_val.setObjectName("l_homeworld_mag_val")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_mag_val, 1, 9, 1, 1)
        self.l_homeworld_chi_val = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_chi_val.setObjectName("l_homeworld_chi_val")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_chi_val, 1, 10, 1, 1)
        self.l_homeworld_psi_val = QtWidgets.QLabel(self.gb_homeworld_stats)
        self.l_homeworld_psi_val.setObjectName("l_homeworld_psi_val")
        self.gl_homeworld_stats.addWidget(self.l_homeworld_psi_val, 1, 11, 1, 1)
        self.vl_homeworld.addWidget(self.gb_homeworld_stats)
        self.tw_main.addTab(self.tab_homeworld, "")
        self.tab_careers = QtWidgets.QWidget()
        self.tab_careers.setObjectName("tab_careers")
        self.vl_careers = QtWidgets.QVBoxLayout(self.tab_careers)
        self.vl_careers.setObjectName("vl_careers")
        self.hl_careers_careers_skills = QtWidgets.QHBoxLayout()
        self.hl_careers_careers_skills.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.hl_careers_careers_skills.setObjectName("hl_careers_careers_skills")
        self.gb_careers_careers = QtWidgets.QGroupBox(self.tab_careers)
        self.gb_careers_careers.setObjectName("gb_careers_careers")
        self.hl_careers_careers = QtWidgets.QHBoxLayout(self.gb_careers_careers)
        self.hl_careers_careers.setObjectName("hl_careers_careers")
        self.lw_careers_careers_val = QtWidgets.QListWidget(self.gb_careers_careers)
        self.lw_careers_careers_val.setObjectName("lw_careers_careers_val")
        self.hl_careers_careers.addWidget(self.lw_careers_careers_val)
        self.vl_careers_buttons = QtWidgets.QVBoxLayout()
        self.vl_careers_buttons.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.vl_careers_buttons.setObjectName("vl_careers_buttons")
        self.pb_careers_add = QtWidgets.QPushButton(self.gb_careers_careers)
        self.pb_careers_add.setObjectName("pb_careers_add")
        self.vl_careers_buttons.addWidget(self.pb_careers_add)
        self.pb_careers_edit = QtWidgets.QPushButton(self.gb_careers_careers)
        self.pb_careers_edit.setObjectName("pb_careers_edit")
        self.vl_careers_buttons.addWidget(self.pb_careers_edit)
        self.pb_careers_remove = QtWidgets.QPushButton(self.gb_careers_careers)
        self.pb_careers_remove.setObjectName("pb_careers_remove")
        self.vl_careers_buttons.addWidget(self.pb_careers_remove)
        self.pb_careers_move_up = QtWidgets.QPushButton(self.gb_careers_careers)
        self.pb_careers_move_up.setObjectName("pb_careers_move_up")
        self.vl_careers_buttons.addWidget(self.pb_careers_move_up)
        self.pb_careers_move_down = QtWidgets.QPushButton(self.gb_careers_careers)
        self.pb_careers_move_down.setObjectName("pb_careers_move_down")
        self.vl_careers_buttons.addWidget(self.pb_careers_move_down)
        self.hl_careers_careers.addLayout(self.vl_careers_buttons)
        self.hl_careers_careers_skills.addWidget(self.gb_careers_careers)
        self.gb_careers_skills = QtWidgets.QGroupBox(self.tab_careers)
        self.gb_careers_skills.setObjectName("gb_careers_skills")
        self.vl_careers_skills = QtWidgets.QVBoxLayout(self.gb_careers_skills)
        self.vl_careers_skills.setObjectName("vl_careers_skills")
        self.pte_careers_skills_val = QtWidgets.QPlainTextEdit(self.gb_careers_skills)
        self.pte_careers_skills_val.setReadOnly(True)
        self.pte_careers_skills_val.setObjectName("pte_careers_skills_val")
        self.vl_careers_skills.addWidget(self.pte_careers_skills_val)
        self.pb_careers_set_skills = QtWidgets.QPushButton(self.gb_careers_skills)
        self.pb_careers_set_skills.setObjectName("pb_careers_set_skills")
        self.vl_careers_skills.addWidget(self.pb_careers_set_skills, 0, QtCore.Qt.AlignLeft)
        self.hl_careers_careers_skills.addWidget(self.gb_careers_skills)
        self.vl_careers.addLayout(self.hl_careers_careers_skills)
        self.gb_careers_exploit = QtWidgets.QGroupBox(self.tab_careers)
        self.gb_careers_exploit.setObjectName("gb_careers_exploit")
        self.vl_careers_exploit = QtWidgets.QVBoxLayout(self.gb_careers_exploit)
        self.vl_careers_exploit.setObjectName("vl_careers_exploit")
        self.pte_careers_exploit_val = QtWidgets.QPlainTextEdit(self.gb_careers_exploit)
        self.pte_careers_exploit_val.setReadOnly(True)
        self.pte_careers_exploit_val.setObjectName("pte_careers_exploit_val")
        self.vl_careers_exploit.addWidget(self.pte_careers_exploit_val)
        self.pb_careers_set_exploit = QtWidgets.QPushButton(self.gb_careers_exploit)
        self.pb_careers_set_exploit.setObjectName("pb_careers_set_exploit")
        self.vl_careers_exploit.addWidget(self.pb_careers_set_exploit, 0, QtCore.Qt.AlignLeft)
        self.vl_careers.addWidget(self.gb_careers_exploit)
        self.gb_careers_stats = QtWidgets.QGroupBox(self.tab_careers)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_careers_stats.sizePolicy().hasHeightForWidth())
        self.gb_careers_stats.setSizePolicy(sizePolicy)
        self.gb_careers_stats.setObjectName("gb_careers_stats")
        self.gl_careers_stats = QtWidgets.QGridLayout(self.gb_careers_stats)
        self.gl_careers_stats.setObjectName("gl_careers_stats")
        self.l_careers_str = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_str.setObjectName("l_careers_str")
        self.gl_careers_stats.addWidget(self.l_careers_str, 0, 0, 1, 1)
        self.l_careers_agi = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_agi.setObjectName("l_careers_agi")
        self.gl_careers_stats.addWidget(self.l_careers_agi, 0, 1, 1, 1)
        self.l_careers_end = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_end.setObjectName("l_careers_end")
        self.gl_careers_stats.addWidget(self.l_careers_end, 0, 2, 1, 1)
        self.l_careers_int = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_int.setObjectName("l_careers_int")
        self.gl_careers_stats.addWidget(self.l_careers_int, 0, 3, 1, 1)
        self.l_careers_log = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_log.setObjectName("l_careers_log")
        self.gl_careers_stats.addWidget(self.l_careers_log, 0, 4, 1, 1)
        self.l_careers_wil = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_wil.setObjectName("l_careers_wil")
        self.gl_careers_stats.addWidget(self.l_careers_wil, 0, 5, 1, 1)
        self.l_careers_cha = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_cha.setObjectName("l_careers_cha")
        self.gl_careers_stats.addWidget(self.l_careers_cha, 0, 6, 1, 1)
        self.l_careers_luc = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_luc.setObjectName("l_careers_luc")
        self.gl_careers_stats.addWidget(self.l_careers_luc, 0, 7, 1, 1)
        self.l_careers_rep = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_rep.setObjectName("l_careers_rep")
        self.gl_careers_stats.addWidget(self.l_careers_rep, 0, 8, 1, 1)
        self.l_careers_mag = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_mag.setObjectName("l_careers_mag")
        self.gl_careers_stats.addWidget(self.l_careers_mag, 0, 9, 1, 1)
        self.l_careers_chi = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_chi.setObjectName("l_careers_chi")
        self.gl_careers_stats.addWidget(self.l_careers_chi, 0, 10, 1, 1)
        self.l_careers_psi = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_psi.setObjectName("l_careers_psi")
        self.gl_careers_stats.addWidget(self.l_careers_psi, 0, 11, 1, 1)
        self.l_careers_str_val = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_str_val.setObjectName("l_careers_str_val")
        self.gl_careers_stats.addWidget(self.l_careers_str_val, 1, 0, 1, 1)
        self.l_careers_agi_val = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_agi_val.setObjectName("l_careers_agi_val")
        self.gl_careers_stats.addWidget(self.l_careers_agi_val, 1, 1, 1, 1)
        self.l_careers_end_val = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_end_val.setObjectName("l_careers_end_val")
        self.gl_careers_stats.addWidget(self.l_careers_end_val, 1, 2, 1, 1)
        self.l_careers_int_val = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_int_val.setObjectName("l_careers_int_val")
        self.gl_careers_stats.addWidget(self.l_careers_int_val, 1, 3, 1, 1)
        self.l_careers_log_val = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_log_val.setObjectName("l_careers_log_val")
        self.gl_careers_stats.addWidget(self.l_careers_log_val, 1, 4, 1, 1)
        self.l_careers_wil_val = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_wil_val.setObjectName("l_careers_wil_val")
        self.gl_careers_stats.addWidget(self.l_careers_wil_val, 1, 5, 1, 1)
        self.l_careers_cha_val = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_cha_val.setObjectName("l_careers_cha_val")
        self.gl_careers_stats.addWidget(self.l_careers_cha_val, 1, 6, 1, 1)
        self.l_careers_luc_val = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_luc_val.setObjectName("l_careers_luc_val")
        self.gl_careers_stats.addWidget(self.l_careers_luc_val, 1, 7, 1, 1)
        self.l_careers_rep_val = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_rep_val.setObjectName("l_careers_rep_val")
        self.gl_careers_stats.addWidget(self.l_careers_rep_val, 1, 8, 1, 1)
        self.l_careers_mag_val = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_mag_val.setObjectName("l_careers_mag_val")
        self.gl_careers_stats.addWidget(self.l_careers_mag_val, 1, 9, 1, 1)
        self.l_careers_chi_val = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_chi_val.setObjectName("l_careers_chi_val")
        self.gl_careers_stats.addWidget(self.l_careers_chi_val, 1, 10, 1, 1)
        self.l_careers_psi_val = QtWidgets.QLabel(self.gb_careers_stats)
        self.l_careers_psi_val.setObjectName("l_careers_psi_val")
        self.gl_careers_stats.addWidget(self.l_careers_psi_val, 1, 11, 1, 1)
        self.vl_careers.addWidget(self.gb_careers_stats)
        self.tw_main.addTab(self.tab_careers, "")
        self.tab_exploits = QtWidgets.QWidget()
        self.tab_exploits.setObjectName("tab_exploits")
        self.hl_exploits = QtWidgets.QHBoxLayout(self.tab_exploits)
        self.hl_exploits.setObjectName("hl_exploits")
        self.gb_exploits_exploits = QtWidgets.QGroupBox(self.tab_exploits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_exploits_exploits.sizePolicy().hasHeightForWidth())
        self.gb_exploits_exploits.setSizePolicy(sizePolicy)
        self.gb_exploits_exploits.setObjectName("gb_exploits_exploits")
        self.formLayout = QtWidgets.QFormLayout(self.gb_exploits_exploits)
        self.formLayout.setObjectName("formLayout")
        self.lw_exploits_exploits_val = QtWidgets.QListWidget(self.gb_exploits_exploits)
        self.lw_exploits_exploits_val.setObjectName("lw_exploits_exploits_val")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lw_exploits_exploits_val)
        self.pb_exploits_add = QtWidgets.QPushButton(self.gb_exploits_exploits)
        self.pb_exploits_add.setObjectName("pb_exploits_add")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pb_exploits_add)
        self.pb_exploits_remove = QtWidgets.QPushButton(self.gb_exploits_exploits)
        self.pb_exploits_remove.setObjectName("pb_exploits_remove")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pb_exploits_remove)
        self.hl_exploits.addWidget(self.gb_exploits_exploits)
        self.gb_exploits_desc = QtWidgets.QGroupBox(self.tab_exploits)
        self.gb_exploits_desc.setObjectName("gb_exploits_desc")
        self.vl_exploits_desc = QtWidgets.QVBoxLayout(self.gb_exploits_desc)
        self.vl_exploits_desc.setObjectName("vl_exploits_desc")
        self.pte_exploits_desc = QtWidgets.QPlainTextEdit(self.gb_exploits_desc)
        self.pte_exploits_desc.setReadOnly(True)
        self.pte_exploits_desc.setObjectName("pte_exploits_desc")
        self.vl_exploits_desc.addWidget(self.pte_exploits_desc)
        self.hl_exploits.addWidget(self.gb_exploits_desc)
        self.tw_main.addTab(self.tab_exploits, "")
        self.tab_equipment = QtWidgets.QWidget()
        self.tab_equipment.setObjectName("tab_equipment")
        self.vl_equipment = QtWidgets.QVBoxLayout(self.tab_equipment)
        self.vl_equipment.setObjectName("vl_equipment")
        self.tw_equipment = QtWidgets.QTabWidget(self.tab_equipment)
        self.tw_equipment.setObjectName("tw_equipment")
        self.tab_equipment_general = QtWidgets.QWidget()
        self.tab_equipment_general.setObjectName("tab_equipment_general")
        self.vl_tab_eq_gn = QtWidgets.QVBoxLayout(self.tab_equipment_general)
        self.vl_tab_eq_gn.setObjectName("vl_tab_eq_gn")
        self.tw_eq_gn_val = QtWidgets.QTreeWidget(self.tab_equipment_general)
        self.tw_eq_gn_val.setObjectName("tw_eq_gn_val")
        self.vl_tab_eq_gn.addWidget(self.tw_eq_gn_val)
        self.hl_eq_gn = QtWidgets.QHBoxLayout()
        self.hl_eq_gn.setObjectName("hl_eq_gn")
        self.pb_eq_gn_add = QtWidgets.QPushButton(self.tab_equipment_general)
        self.pb_eq_gn_add.setObjectName("pb_eq_gn_add")
        self.hl_eq_gn.addWidget(self.pb_eq_gn_add)
        self.pb_eq_gn_remove = QtWidgets.QPushButton(self.tab_equipment_general)
        self.pb_eq_gn_remove.setObjectName("pb_eq_gn_remove")
        self.hl_eq_gn.addWidget(self.pb_eq_gn_remove)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_eq_gn.addItem(spacerItem)
        self.vl_tab_eq_gn.addLayout(self.hl_eq_gn)
        self.tw_equipment.addTab(self.tab_equipment_general, "")
        self.tab_equipment_weapons = QtWidgets.QWidget()
        self.tab_equipment_weapons.setObjectName("tab_equipment_weapons")
        self.vl_tab_eq_wp = QtWidgets.QVBoxLayout(self.tab_equipment_weapons)
        self.vl_tab_eq_wp.setObjectName("vl_tab_eq_wp")
        self.tw_eq_wp_val = QtWidgets.QTreeWidget(self.tab_equipment_weapons)
        self.tw_eq_wp_val.setObjectName("tw_eq_wp_val")
        self.vl_tab_eq_wp.addWidget(self.tw_eq_wp_val)
        self.hl_eq_wp = QtWidgets.QHBoxLayout()
        self.hl_eq_wp.setObjectName("hl_eq_wp")
        self.pb_eq_wp_add = QtWidgets.QPushButton(self.tab_equipment_weapons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_eq_wp_add.sizePolicy().hasHeightForWidth())
        self.pb_eq_wp_add.setSizePolicy(sizePolicy)
        self.pb_eq_wp_add.setObjectName("pb_eq_wp_add")
        self.hl_eq_wp.addWidget(self.pb_eq_wp_add)
        self.pb_eq_wp_remove = QtWidgets.QPushButton(self.tab_equipment_weapons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_eq_wp_remove.sizePolicy().hasHeightForWidth())
        self.pb_eq_wp_remove.setSizePolicy(sizePolicy)
        self.pb_eq_wp_remove.setObjectName("pb_eq_wp_remove")
        self.hl_eq_wp.addWidget(self.pb_eq_wp_remove)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_eq_wp.addItem(spacerItem1)
        self.vl_tab_eq_wp.addLayout(self.hl_eq_wp)
        self.gb_eq_wp_ammo = QtWidgets.QGroupBox(self.tab_equipment_weapons)
        self.gb_eq_wp_ammo.setObjectName("gb_eq_wp_ammo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gb_eq_wp_ammo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_eq_wp_ammo = QtWidgets.QLabel(self.gb_eq_wp_ammo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_eq_wp_ammo.sizePolicy().hasHeightForWidth())
        self.l_eq_wp_ammo.setSizePolicy(sizePolicy)
        self.l_eq_wp_ammo.setObjectName("l_eq_wp_ammo")
        self.verticalLayout.addWidget(self.l_eq_wp_ammo)
        self.gl_ammo_type = QtWidgets.QGridLayout()
        self.gl_ammo_type.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gl_ammo_type.setObjectName("gl_ammo_type")
        self.sb_eq_wp_magazine_val = QtWidgets.QSpinBox(self.gb_eq_wp_ammo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_eq_wp_magazine_val.sizePolicy().hasHeightForWidth())
        self.sb_eq_wp_magazine_val.setSizePolicy(sizePolicy)
        self.sb_eq_wp_magazine_val.setMinimum(1)
        self.sb_eq_wp_magazine_val.setObjectName("sb_eq_wp_magazine_val")
        self.gl_ammo_type.addWidget(self.sb_eq_wp_magazine_val, 1, 1, 1, 1)
        self.l_eq_wp_magazine = QtWidgets.QLabel(self.gb_eq_wp_ammo)
        self.l_eq_wp_magazine.setObjectName("l_eq_wp_magazine")
        self.gl_ammo_type.addWidget(self.l_eq_wp_magazine, 0, 1, 1, 1)
        self.l_eq_wp_ammo_type = QtWidgets.QLabel(self.gb_eq_wp_ammo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_eq_wp_ammo_type.sizePolicy().hasHeightForWidth())
        self.l_eq_wp_ammo_type.setSizePolicy(sizePolicy)
        self.l_eq_wp_ammo_type.setObjectName("l_eq_wp_ammo_type")
        self.gl_ammo_type.addWidget(self.l_eq_wp_ammo_type, 0, 0, 1, 1)
        self.cb_eq_wp_ammo_type_val = QtWidgets.QComboBox(self.gb_eq_wp_ammo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_eq_wp_ammo_type_val.sizePolicy().hasHeightForWidth())
        self.cb_eq_wp_ammo_type_val.setSizePolicy(sizePolicy)
        self.cb_eq_wp_ammo_type_val.setObjectName("cb_eq_wp_ammo_type_val")
        self.cb_eq_wp_ammo_type_val.addItem("")
        self.cb_eq_wp_ammo_type_val.addItem("")
        self.cb_eq_wp_ammo_type_val.addItem("")
        self.cb_eq_wp_ammo_type_val.addItem("")
        self.cb_eq_wp_ammo_type_val.addItem("")
        self.gl_ammo_type.addWidget(self.cb_eq_wp_ammo_type_val, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gl_ammo_type.addItem(spacerItem2, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gl_ammo_type)
        self.hl_eq_wp_ammo = QtWidgets.QHBoxLayout()
        self.hl_eq_wp_ammo.setObjectName("hl_eq_wp_ammo")
        self.pb_eq_wp_ammo_add = QtWidgets.QPushButton(self.gb_eq_wp_ammo)
        self.pb_eq_wp_ammo_add.setObjectName("pb_eq_wp_ammo_add")
        self.hl_eq_wp_ammo.addWidget(self.pb_eq_wp_ammo_add)
        self.pb_eq_wp_ammo_remove = QtWidgets.QPushButton(self.gb_eq_wp_ammo)
        self.pb_eq_wp_ammo_remove.setObjectName("pb_eq_wp_ammo_remove")
        self.hl_eq_wp_ammo.addWidget(self.pb_eq_wp_ammo_remove)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_eq_wp_ammo.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.hl_eq_wp_ammo)
        self.vl_tab_eq_wp.addWidget(self.gb_eq_wp_ammo)
        self.tw_equipment.addTab(self.tab_equipment_weapons, "")
        self.tab_equipment_armor = QtWidgets.QWidget()
        self.tab_equipment_armor.setObjectName("tab_equipment_armor")
        self.vl_tab_eq_ar = QtWidgets.QVBoxLayout(self.tab_equipment_armor)
        self.vl_tab_eq_ar.setObjectName("vl_tab_eq_ar")
        self.tw_eq_ar_val = QtWidgets.QTreeWidget(self.tab_equipment_armor)
        self.tw_eq_ar_val.setObjectName("tw_eq_ar_val")
        self.vl_tab_eq_ar.addWidget(self.tw_eq_ar_val)
        self.hl_eq_ar = QtWidgets.QHBoxLayout()
        self.hl_eq_ar.setObjectName("hl_eq_ar")
        self.pb_eq_ar_add = QtWidgets.QPushButton(self.tab_equipment_armor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_eq_ar_add.sizePolicy().hasHeightForWidth())
        self.pb_eq_ar_add.setSizePolicy(sizePolicy)
        self.pb_eq_ar_add.setObjectName("pb_eq_ar_add")
        self.hl_eq_ar.addWidget(self.pb_eq_ar_add)
        self.pb_eq_ar_remove = QtWidgets.QPushButton(self.tab_equipment_armor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_eq_ar_remove.sizePolicy().hasHeightForWidth())
        self.pb_eq_ar_remove.setSizePolicy(sizePolicy)
        self.pb_eq_ar_remove.setObjectName("pb_eq_ar_remove")
        self.hl_eq_ar.addWidget(self.pb_eq_ar_remove)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_eq_ar.addItem(spacerItem4)
        self.vl_tab_eq_ar.addLayout(self.hl_eq_ar)
        self.tw_equipment.addTab(self.tab_equipment_armor, "")
        self.vl_equipment.addWidget(self.tw_equipment)
        self.tw_main.addTab(self.tab_equipment, "")
        self.vl_central_widget.addWidget(self.tw_main)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1051, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setEnabled(False)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setEnabled(False)
        self.actionExport.setObjectName("actionExport")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tw_main.setCurrentIndex(0)
        self.tw_equipment.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WOIN Character Assistant"))
        self.gb_overview_info.setTitle(_translate("MainWindow", "Info"))
        self.l_overview_name.setText(_translate("MainWindow", "Name"))
        self.l_overview_race.setText(_translate("MainWindow", "Race"))
        self.l_overview_homeworld.setText(_translate("MainWindow", "Homeworld"))
        self.l_overview_trait.setText(_translate("MainWindow", "Trait"))
        self.pb_overview_trait_val.setText(_translate("MainWindow", "trait_val"))
        self.l_overview_hook.setText(_translate("MainWindow", "Hook"))
        self.l_overview_race_val.setText(_translate("MainWindow", "race_val"))
        self.l_overview_homeworld_val.setText(_translate("MainWindow", "homeworld_val"))
        self.gb_overview_skills.setTitle(_translate("MainWindow", "Skills"))
        self.gb_overview_exploits.setTitle(_translate("MainWindow", "Exploits"))
        self.gb_overview_derived_stats.setTitle(_translate("MainWindow", "Derived Statistics"))
        self.gb_overview_health.setTitle(_translate("MainWindow", "Health"))
        self.l_overview_health_val.setText(_translate("MainWindow", "health_val"))
        self.gb_overview_initiative.setTitle(_translate("MainWindow", "Initiative"))
        self.l_overview_initiative_val.setText(_translate("MainWindow", "initiative_val"))
        self.gb_overview_movement.setTitle(_translate("MainWindow", "Movement"))
        self.l_overview_speed.setText(_translate("MainWindow", "Speed"))
        self.l_overview_speed_val.setText(_translate("MainWindow", "speed_val"))
        self.l_overview_climb.setText(_translate("MainWindow", "Climb"))
        self.l_overview_swim.setText(_translate("MainWindow", "Swim"))
        self.l_overview_zlhg.setText(_translate("MainWindow", "Zero/Low/High-G"))
        self.l_overview_vertical_jump.setText(_translate("MainWindow", "Vertical Jump (Running)"))
        self.l_overview_horizontal_jump.setText(_translate("MainWindow", "Horizontal Jump (Running)"))
        self.l_overview_carry.setText(_translate("MainWindow", "Carry"))
        self.l_overview_climb_val.setText(_translate("MainWindow", "climb_val"))
        self.l_overview_swim_val.setText(_translate("MainWindow", "swim_val"))
        self.l_overview_zlhg_val.setText(_translate("MainWindow", "zlhg_val"))
        self.l_overview_vertical_jump_val.setText(_translate("MainWindow", "vj_val"))
        self.l_overview_horizontal_jump_val.setText(_translate("MainWindow", "hj_val"))
        self.l_overview_carry_val.setText(_translate("MainWindow", "carry_val"))
        self.gb_overview_defenses.setTitle(_translate("MainWindow", "Defenses"))
        self.l_overview_melee_def.setText(_translate("MainWindow", "Melee"))
        self.l_overview_melee_def_val.setText(_translate("MainWindow", "melee_val"))
        self.l_overview_ranged_def.setText(_translate("MainWindow", "Ranged"))
        self.l_overview_ranged_def_val.setText(_translate("MainWindow", "ranged_val"))
        self.l_overview_mental_def.setText(_translate("MainWindow", "Mental"))
        self.l_overview_mental_def_val.setText(_translate("MainWindow", "mental_val"))
        self.l_overview_vital_def.setText(_translate("MainWindow", "Vital"))
        self.l_overview_vital_def_val.setText(_translate("MainWindow", "vital_val"))
        self.pb_set_defense_skills.setText(_translate("MainWindow", "Set Defense Skills"))
        self.gb_overview_stats.setTitle(_translate("MainWindow", "Total Stats"))
        self.l_overview_rep.setText(_translate("MainWindow", "REP"))
        self.l_overview_cha.setText(_translate("MainWindow", "CHA"))
        self.l_overview_psi.setText(_translate("MainWindow", "PSI"))
        self.l_overview_chi.setText(_translate("MainWindow", "CHI"))
        self.l_overview_end.setText(_translate("MainWindow", "END"))
        self.l_overview_int.setText(_translate("MainWindow", "INT"))
        self.l_overview_mag.setText(_translate("MainWindow", "MAG"))
        self.l_overview_str.setText(_translate("MainWindow", "STR"))
        self.l_overview_wil.setText(_translate("MainWindow", "WIL"))
        self.l_overview_agi.setText(_translate("MainWindow", "AGI"))
        self.l_overview_log.setText(_translate("MainWindow", "LOG"))
        self.l_overview_luc.setText(_translate("MainWindow", "LUC"))
        self.l_overview_str_val.setText(_translate("MainWindow", "str_val"))
        self.l_overview_agi_val.setText(_translate("MainWindow", "agi_val"))
        self.l_overview_end_val.setText(_translate("MainWindow", "end_val"))
        self.l_overview_int_val.setText(_translate("MainWindow", "int_val"))
        self.l_overview_log_val.setText(_translate("MainWindow", "log_val"))
        self.l_overview_wil_val.setText(_translate("MainWindow", "wil_val"))
        self.l_overview_cha_val.setText(_translate("MainWindow", "cha_val"))
        self.l_overview_luc_val.setText(_translate("MainWindow", "luc_val"))
        self.l_overview_rep_val.setText(_translate("MainWindow", "rep_val"))
        self.l_overview_mag_val.setText(_translate("MainWindow", "mag_val"))
        self.l_overview_chi_val.setText(_translate("MainWindow", "chi_val"))
        self.l_overview_psi_val.setText(_translate("MainWindow", "psi_val"))
        self.tw_main.setTabText(self.tw_main.indexOf(self.tab_overview), _translate("MainWindow", "Overview"))
        self.gb_race_race.setTitle(_translate("MainWindow", "Race"))
        self.l_race_race.setText(_translate("MainWindow", "Race Name"))
        self.pb_race_race_val.setText(_translate("MainWindow", "race_val"))
        self.l_race_size.setText(_translate("MainWindow", "Size"))
        self.cb_race_size_val.setCurrentText(_translate("MainWindow", "Tiny"))
        self.cb_race_size_val.setItemText(0, _translate("MainWindow", "Tiny"))
        self.cb_race_size_val.setItemText(1, _translate("MainWindow", "Small"))
        self.cb_race_size_val.setItemText(2, _translate("MainWindow", "Medium"))
        self.cb_race_size_val.setItemText(3, _translate("MainWindow", "Large"))
        self.cb_race_size_val.setItemText(4, _translate("MainWindow", "Enormous"))
        self.cb_race_size_val.setItemText(5, _translate("MainWindow", "Gigantic"))
        self.cb_race_size_val.setItemText(6, _translate("MainWindow", "Colossal"))
        self.cb_race_size_val.setItemText(7, _translate("MainWindow", "Titanic"))
        self.gb_race_skills.setTitle(_translate("MainWindow", "Selected Skills"))
        self.pb_race_set_skills.setText(_translate("MainWindow", "Set Race Skills"))
        self.gb_race_exploits.setTitle(_translate("MainWindow", "Exploits"))
        self.gb_race_exploits_desc.setTitle(_translate("MainWindow", "Description"))
        self.gb_race_stats.setTitle(_translate("MainWindow", "Racial Stats"))
        self.l_race_str.setText(_translate("MainWindow", "STR"))
        self.l_race_agi.setText(_translate("MainWindow", "AGI"))
        self.l_race_end.setText(_translate("MainWindow", "END"))
        self.l_race_int.setText(_translate("MainWindow", "INT"))
        self.l_race_log.setText(_translate("MainWindow", "LOG"))
        self.l_race_will.setText(_translate("MainWindow", "WIL"))
        self.l_race_cha.setText(_translate("MainWindow", "CHA"))
        self.l_race_luc.setText(_translate("MainWindow", "LUC"))
        self.l_race_rep.setText(_translate("MainWindow", "REP"))
        self.l_race_mag.setText(_translate("MainWindow", "MAG"))
        self.l_race_chi.setText(_translate("MainWindow", "CHI"))
        self.l_race_psi.setText(_translate("MainWindow", "PSI"))
        self.l_race_str_val.setText(_translate("MainWindow", "str_val"))
        self.l_race_agi_val.setText(_translate("MainWindow", "agi_val"))
        self.l_race_end_val.setText(_translate("MainWindow", "end_val"))
        self.l_race_int_val.setText(_translate("MainWindow", "int_val"))
        self.l_race_log_val.setText(_translate("MainWindow", "log_val"))
        self.l_race_wil_val.setText(_translate("MainWindow", "wil_val"))
        self.l_race_cha_val.setText(_translate("MainWindow", "cha_val"))
        self.l_race_luc_val.setText(_translate("MainWindow", "luc_val"))
        self.l_race_rep_val.setText(_translate("MainWindow", "rep_val"))
        self.l_race_mag_val.setText(_translate("MainWindow", "mag_val"))
        self.l_race_chi_val.setText(_translate("MainWindow", "chi_val"))
        self.l_race_psi_val.setText(_translate("MainWindow", "psi_val"))
        self.tw_main.setTabText(self.tw_main.indexOf(self.tab_race), _translate("MainWindow", "Race"))
        self.gb_homeworld_homeworld.setTitle(_translate("MainWindow", "Homeworld"))
        self.pb_homeworld_homeworld_val.setText(_translate("MainWindow", "homeworld_val"))
        self.gb_homeworld_skills.setTitle(_translate("MainWindow", "Selected Skills"))
        self.pb_homeworld_set_skills.setText(_translate("MainWindow", "Set Homeworld Skills"))
        self.gb_homeworld_stats.setTitle(_translate("MainWindow", "Homeworld Stats"))
        self.l_homeworld_str.setText(_translate("MainWindow", "STR"))
        self.l_homeworld_agi.setText(_translate("MainWindow", "AGI"))
        self.l_homeworld_end.setText(_translate("MainWindow", "END"))
        self.l_homeworld_int.setText(_translate("MainWindow", "INT"))
        self.l_homeworld_log.setText(_translate("MainWindow", "LOG"))
        self.l_homeworld_wil.setText(_translate("MainWindow", "WIL"))
        self.l_homeworld_cha.setText(_translate("MainWindow", "CHA"))
        self.l_homeworld_luc.setText(_translate("MainWindow", "LUC"))
        self.l_homeworld_rep.setText(_translate("MainWindow", "REP"))
        self.l_homeworld_mag.setText(_translate("MainWindow", "MAG"))
        self.l_homeworld_chi.setText(_translate("MainWindow", "CHI"))
        self.l_homeworld_psi.setText(_translate("MainWindow", "PSI"))
        self.l_homeworld_str_val.setText(_translate("MainWindow", "str_val"))
        self.l_homeworld_agi_val.setText(_translate("MainWindow", "agi_val"))
        self.l_homeworld_end_val.setText(_translate("MainWindow", "end_val"))
        self.l_homeworld_int_val.setText(_translate("MainWindow", "int_val"))
        self.l_homeworld_log_val.setText(_translate("MainWindow", "log_val"))
        self.l_homeworld_wil_val.setText(_translate("MainWindow", "wil_val"))
        self.l_homeworld_cha_val.setText(_translate("MainWindow", "cha_val"))
        self.l_homeworld_luc_val.setText(_translate("MainWindow", "luc_val"))
        self.l_homeworld_rep_val.setText(_translate("MainWindow", "rep_val"))
        self.l_homeworld_mag_val.setText(_translate("MainWindow", "mag_val"))
        self.l_homeworld_chi_val.setText(_translate("MainWindow", "chi_val"))
        self.l_homeworld_psi_val.setText(_translate("MainWindow", "psi_val"))
        self.tw_main.setTabText(self.tw_main.indexOf(self.tab_homeworld), _translate("MainWindow", "Homeworld"))
        self.gb_careers_careers.setTitle(_translate("MainWindow", "Careers"))
        self.pb_careers_add.setText(_translate("MainWindow", "Add"))
        self.pb_careers_edit.setText(_translate("MainWindow", "Edit"))
        self.pb_careers_remove.setText(_translate("MainWindow", "Remove"))
        self.pb_careers_move_up.setText(_translate("MainWindow", "Move Up"))
        self.pb_careers_move_down.setText(_translate("MainWindow", "Move Down"))
        self.gb_careers_skills.setTitle(_translate("MainWindow", "Skills"))
        self.pb_careers_set_skills.setText(_translate("MainWindow", "Set Career Skills"))
        self.gb_careers_exploit.setTitle(_translate("MainWindow", "Exploit"))
        self.pb_careers_set_exploit.setText(_translate("MainWindow", "Set Career Exploit"))
        self.gb_careers_stats.setTitle(_translate("MainWindow", "Career Stats"))
        self.l_careers_str.setText(_translate("MainWindow", "STR"))
        self.l_careers_agi.setText(_translate("MainWindow", "AGI"))
        self.l_careers_end.setText(_translate("MainWindow", "END"))
        self.l_careers_int.setText(_translate("MainWindow", "INT"))
        self.l_careers_log.setText(_translate("MainWindow", "LOG"))
        self.l_careers_wil.setText(_translate("MainWindow", "WIL"))
        self.l_careers_cha.setText(_translate("MainWindow", "CHA"))
        self.l_careers_luc.setText(_translate("MainWindow", "LUC"))
        self.l_careers_rep.setText(_translate("MainWindow", "REP"))
        self.l_careers_mag.setText(_translate("MainWindow", "MAG"))
        self.l_careers_chi.setText(_translate("MainWindow", "CHI"))
        self.l_careers_psi.setText(_translate("MainWindow", "PSI"))
        self.l_careers_str_val.setText(_translate("MainWindow", "str_val"))
        self.l_careers_agi_val.setText(_translate("MainWindow", "agi_val"))
        self.l_careers_end_val.setText(_translate("MainWindow", "end_val"))
        self.l_careers_int_val.setText(_translate("MainWindow", "int_val"))
        self.l_careers_log_val.setText(_translate("MainWindow", "log_val"))
        self.l_careers_wil_val.setText(_translate("MainWindow", "wil_val"))
        self.l_careers_cha_val.setText(_translate("MainWindow", "cha_val"))
        self.l_careers_luc_val.setText(_translate("MainWindow", "luc_val"))
        self.l_careers_rep_val.setText(_translate("MainWindow", "rep_val"))
        self.l_careers_mag_val.setText(_translate("MainWindow", "mag_val"))
        self.l_careers_chi_val.setText(_translate("MainWindow", "chi_val"))
        self.l_careers_psi_val.setText(_translate("MainWindow", "psi_val"))
        self.tw_main.setTabText(self.tw_main.indexOf(self.tab_careers), _translate("MainWindow", "Careers"))
        self.gb_exploits_exploits.setTitle(_translate("MainWindow", "Exploits"))
        self.pb_exploits_add.setText(_translate("MainWindow", "Add..."))
        self.pb_exploits_remove.setText(_translate("MainWindow", "Remove"))
        self.gb_exploits_desc.setTitle(_translate("MainWindow", "Description"))
        self.tw_main.setTabText(self.tw_main.indexOf(self.tab_exploits), _translate("MainWindow", "Exploits"))
        self.tw_eq_gn_val.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.tw_eq_gn_val.headerItem().setText(1, _translate("MainWindow", "Weight Per Unit"))
        self.tw_eq_gn_val.headerItem().setText(2, _translate("MainWindow", "Quantity"))
        self.tw_eq_gn_val.headerItem().setText(3, _translate("MainWindow", "Total Cost"))
        self.pb_eq_gn_add.setText(_translate("MainWindow", "Add"))
        self.pb_eq_gn_remove.setText(_translate("MainWindow", "Remove"))
        self.tw_equipment.setTabText(self.tw_equipment.indexOf(self.tab_equipment_general), _translate("MainWindow", "General"))
        self.tw_eq_wp_val.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.tw_eq_wp_val.headerItem().setText(1, _translate("MainWindow", "Damage"))
        self.tw_eq_wp_val.headerItem().setText(2, _translate("MainWindow", "Type"))
        self.tw_eq_wp_val.headerItem().setText(3, _translate("MainWindow", "Range"))
        self.tw_eq_wp_val.headerItem().setText(4, _translate("MainWindow", "Special"))
        self.tw_eq_wp_val.headerItem().setText(5, _translate("MainWindow", "Quantity"))
        self.tw_eq_wp_val.headerItem().setText(6, _translate("MainWindow", "Total Cost"))
        self.tw_eq_wp_val.headerItem().setText(7, _translate("MainWindow", "Total Weight"))
        self.pb_eq_wp_add.setText(_translate("MainWindow", "Add"))
        self.pb_eq_wp_remove.setText(_translate("MainWindow", "Remove"))
        self.gb_eq_wp_ammo.setTitle(_translate("MainWindow", "Ammunition"))
        self.l_eq_wp_ammo.setText(_translate("MainWindow", "Ammo types only apply to weapons with the ballistic damage type."))
        self.l_eq_wp_magazine.setText(_translate("MainWindow", "Magazines/Clips"))
        self.l_eq_wp_ammo_type.setText(_translate("MainWindow", "Type"))
        self.cb_eq_wp_ammo_type_val.setItemText(0, _translate("MainWindow", "Standard"))
        self.cb_eq_wp_ammo_type_val.setItemText(1, _translate("MainWindow", "Armor Piercing"))
        self.cb_eq_wp_ammo_type_val.setItemText(2, _translate("MainWindow", "Hollow Point"))
        self.cb_eq_wp_ammo_type_val.setItemText(3, _translate("MainWindow", "Rubber Bullets"))
        self.cb_eq_wp_ammo_type_val.setItemText(4, _translate("MainWindow", "Tracers"))
        self.pb_eq_wp_ammo_add.setText(_translate("MainWindow", "Add Ammo"))
        self.pb_eq_wp_ammo_remove.setText(_translate("MainWindow", "Remove Selected Ammo"))
        self.tw_equipment.setTabText(self.tw_equipment.indexOf(self.tab_equipment_weapons), _translate("MainWindow", "Weapons"))
        self.tw_eq_ar_val.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.tw_eq_ar_val.headerItem().setText(1, _translate("MainWindow", "Soak"))
        self.tw_eq_ar_val.headerItem().setText(2, _translate("MainWindow", "Defense"))
        self.tw_eq_ar_val.headerItem().setText(3, _translate("MainWindow", "Speed"))
        self.tw_eq_ar_val.headerItem().setText(4, _translate("MainWindow", "Type"))
        self.tw_eq_ar_val.headerItem().setText(5, _translate("MainWindow", "Special"))
        self.tw_eq_ar_val.headerItem().setText(6, _translate("MainWindow", "Quantity"))
        self.tw_eq_ar_val.headerItem().setText(7, _translate("MainWindow", "Total Cost"))
        self.tw_eq_ar_val.headerItem().setText(8, _translate("MainWindow", "Total Weight"))
        self.pb_eq_ar_add.setText(_translate("MainWindow", "Add"))
        self.pb_eq_ar_remove.setText(_translate("MainWindow", "Remove"))
        self.tw_equipment.setTabText(self.tw_equipment.indexOf(self.tab_equipment_armor), _translate("MainWindow", "Armor"))
        self.tw_main.setTabText(self.tw_main.indexOf(self.tab_equipment), _translate("MainWindow", "Equipment"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionExport.setText(_translate("MainWindow", "Export..."))
        self.actionExport.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

